Repository RedisGraph/RedisGraph, pull requests merged in 2018-08, with the labels that each got.

#72 store source nodes as columns and destination nodes as rows
  src/arithmetic/algebraic_expression.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/op_traverse.c
  src/execution_plan/optimizations/translate_filters.c
  src/graph/graph.c
  src/graph/graph.h
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_graph.cpp
Labels: enhancement

#73 pick node with filter applied to it as entry point
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_produce_results.c
  src/execution_plan/optimizations/optimizations.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/reduce_scans.c
  src/execution_plan/optimizations/reduce_scans.h
  src/execution_plan/optimizations/select_entry_point.c
  src/execution_plan/optimizations/select_entry_point.h
  src/execution_plan/optimizations/translate_filters.c
  src/execution_plan/optimizations/translate_filters.h
  src/execution_plan/optimizations/traverse_order.c
  src/filter_tree/filter_tree.c
  src/resultset/resultset.c
  src/resultset/resultset.h
Labels: enhancement

#82 translate merge before naming anonymous nodes
  src/query_executor.c
Labels: bug

#84 verify referenced functions exists
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/arithmetic/repository.c
  src/arithmetic/repository.h
  src/parser/ast.c
  src/parser/ast_arithmetic_expression.c
  src/parser/ast_arithmetic_expression.h
  src/parser/clauses/return.c
  src/parser/clauses/return.h
  src/parser/clauses/set.c
  tests/flow/test_query_validation.py
Labels: bug

#75 support concurrent queries using read/write lock and pthreads
  demo/social/social_queries.py
  src/Makefile
  src/bulk_insert/bulk_insert.c
  src/bulk_insert/bulk_insert.h
  src/bulk_insert/bulk_insert_context.c
  src/bulk_insert/bulk_insert_context.h
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_aggregate.h
  src/grouping/group.h
  src/grouping/group_cache.c
  src/grouping/group_cache.h
  src/module.c
  src/parser/ast.c
  src/parser/ast.h
  src/parser/lexer.l
  src/query_executor.c
  src/query_executor.h
  src/redismodule.h
  src/resultset/resultset.c
  src/resultset/resultset.h
  src/util/thpool/thpool.c
  src/util/thpool/thpool.h
  tests/flow/base.py
  tests/flow/test_concurrent_query.py
Labels: enhancement

#89 Delete graph
  demo/bulk_insert/requirements.txt
  demo/imdb/requirements.txt
  demo/social/requirements.txt
  docs/commands.md
  src/delete_graph.c
  src/delete_graph.h
  src/graph/graph.c
  src/module.c
  src/stores/store.c
  src/stores/store.h
  tests/flow/requirements.txt
  tests/flow/test_concurrent_query.py
  tests/flow/test_graph_deletion.py
Labels: enhancement

#90 multiply by label matrix to the right
  demo/imdb/imdb_queries.py
  demo/social/social_queries.py
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  src/bulk_insert/bulk_insert.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_create.c
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graph_type.c
  tests/unit/test_algebraic_expression.cpp
Labels: bug, enhancement

#91 verify created edge has one relation type
  src/parser/ast.c
  tests/flow/test_query_validation.py
Labels: bug, enhancement

#93 matrix resize guard by critical section
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_delete.h
  src/graph/edge.h
  src/graph/graph.c
  src/graph/graph.h
  src/graph/query_graph.c
  tests/flow/test_graph_deletion.py
  tests/unit/test_graph.cpp
Labels: bug

#92 grammar allow edge to have attributes
  src/parser/grammar.c
  src/parser/grammar.y
  src/parser/lex.yy.c
Labels: enhancement

#113 Strict return validations
  src/module.c
  src/parser/ast.c
  src/parser/clauses/match.c
  src/parser/clauses/return.c
  src/query_executor.c
Labels: bug

#99 Simplify node deletion and reset explicit 0 values in matrices
  demo/social/social_queries.py
  src/graph/graph.c
  tests/flow/test_social.py
  tests/unit/test_graph.cpp
Labels: bug
