Repository RedisGraph/RedisGraph, pull requests merged in 2018-12, with the labels that each got.

#277 Compile GraphBLAS with GBCOMPACT, define boolean structured compile t…
  deps/GraphBLAS/Include/GraphBLAS.h
  deps/GraphBLAS/Source/all_user_objects.c
  deps/GraphBLAS/User/rg_structured_bool.m4
  src/Makefile
  src/arithmetic/algebraic_expression.c
Labels: enhancement

#281 Bulk process csvs
  demo/bulk_insert/README.md
  demo/bulk_insert/bulk_insert.py
  demo/bulk_insert/country.csv
  demo/bulk_insert/know.csv
  demo/bulk_insert/married.csv
  demo/bulk_insert/person.csv
  demo/bulk_insert/resources/Country.csv
  demo/bulk_insert/resources/KNOWS.csv
  demo/bulk_insert/resources/Person.csv
  demo/bulk_insert/resources/VISITED.csv
  demo/bulk_insert/visit.csv
  src/bulk_insert/bulk_insert.c
  src/bulk_insert/bulk_insert.h
  src/commands/cmd_bulk_insert.c
  tests/flow/test_bulk_insertion.py
Labels: enhancement

#280 parse multiple relationship types
  demo/social/social_queries.py
  src/algorithms/all_paths.c
  src/algorithms/all_paths.h
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_cond_var_len_traverse.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_traverse.h
  src/graph/query_graph.c
  src/parser/ast_common.c
  src/parser/ast_common.h
  src/parser/grammar.c
  src/parser/grammar.h
  src/parser/grammar.y
  src/parser/lex.yy.c
  src/parser/lexer.l
  tests/flow/test_social.py
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_all_paths.cpp
  tests/unit/test_arithmetic_expression.cpp
Labels: cypher, enhancement

#289 Index now stores copy of lower bound to properly reset
  src/util/skiplist.c
Labels: bug

#296 Qa automation
  .circleci/config.yml
Labels: enhancement

#288 Multiple relationship types
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  tests/unit/test_algebraic_expression.cpp
Labels: enhancement

#299 Execution plan operation returns record
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_aggregate.h
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_all_node_scan.h
  src/execution_plan/ops/op_cartesian_product.c
  src/execution_plan/ops/op_cartesian_product.h
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_cond_var_len_traverse.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_create.h
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_delete.h
  src/execution_plan/ops/op_filter.c
  src/execution_plan/ops/op_filter.h
  src/execution_plan/ops/op_index_scan.c
  src/execution_plan/ops/op_index_scan.h
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_merge.h
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/op_node_by_label_scan.h
  src/execution_plan/ops/op_produce_results.c
  src/execution_plan/ops/op_produce_results.h
  src/execution_plan/ops/op_traverse.c
  src/execution_plan/ops/op_traverse.h
  src/execution_plan/ops/op_unwind.c
  src/execution_plan/ops/op_unwind.h
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_update.h
  src/execution_plan/record.c
  src/execution_plan/record.h
Labels: enhancement

#275 aggregate and orderby execution plan operations will consume all reco…
  src/arithmetic/aggregate.h
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/commands/cmd_query.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_aggregate.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/op_produce_results.c
  src/execution_plan/ops/op_produce_results.h
  src/execution_plan/ops/op_project.c
  src/execution_plan/ops/op_project.h
  src/execution_plan/ops/op_sort.c
  src/execution_plan/ops/op_sort.h
  src/execution_plan/ops/ops.h
  src/execution_plan/optimizations/utilize_indices.c
  src/execution_plan/record.c
  src/execution_plan/record.h
  src/graph/entities/node.h
  src/grouping/group.c
  src/grouping/group.h
  src/grouping/group_cache.c
  src/grouping/group_cache.h
  src/parser/ast.c
  src/parser/clauses/order.c
  src/parser/clauses/order.h
  src/parser/clauses/return.c
  src/parser/clauses/return.h
  src/parser/grammar.c
  src/parser/grammar.y
  src/query_executor.c
  src/resultset/resultset.c
  src/resultset/resultset.h
  src/resultset/resultset_header.h
  src/resultset/resultset_record.c
  src/resultset/resultset_record.h
  tests/flow/test_bulk_insertion.py
  tests/flow/test_index_scans.py
  tests/flow/test_index_updates.py
  tests/unit/test_aggregate_functions.cpp
  tests/unit/test_arithmetic_expression.cpp
  tests/unit/test_record.cpp
Labels: bug, enhancement
