Repository RedisGraph/RedisGraph, pull requests merged in 2018-11, with the labels that each got.

#198 Don't allow entities to be referenced by multiple match patterns
  src/parser/ast.c
  tests/flow/test_multi_pattern.py
Labels: bug

#202 Bulk insert and graph deletion don't synchronize matrices
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_delete.c
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graphcontext.c
  src/graph/serializers/graphcontext_type.c
Labels: enhancement

#207 #195, increase parser recursion depth
  src/parser/grammar.c
  src/parser/grammar.y
Labels: bug, enhancement

#213 check for relation batch completion before moving to the next section
  src/bulk_insert/bulk_insert.c
Labels: bug

#214 Fixes around FLUSH logic
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_delete.c
  src/graph/graph.c
  src/graph/serializers/serialize_graph.c
  src/stores/store.c
Labels: bug

#224 Verify that argument is valid for aggregate count op
  src/arithmetic/agg_funcs.c
  tests/unit/test_aggregate_functions.cpp
Labels: bug

#227 save graph context within thread local storage, in addition support l…
  demo/social/social_queries.py
  docs/commands.md
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/graph/serializers/serialize_graph.c
  src/module.c
  tests/flow/test_social.py
Labels: enhancement

#228 switch from expect to assert
  tests/unit/test_aggregate_functions.cpp
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_all_paths.cpp
  tests/unit/test_arithmetic_expression.cpp
  tests/unit/test_datablock.cpp
  tests/unit/test_filter_tree.cpp
  tests/unit/test_graph.cpp
  tests/unit/test_gxb_matrix_del.cpp
  tests/unit/test_index.cpp
  tests/unit/test_resultset_record.cpp
  tests/unit/test_skiplist.cpp
  tests/unit/test_tuples_iter.cpp
  tests/unit/test_value.cpp
Labels: enhancement

#229 For the most part calls to RedisModule_LoadStringBuffer need to be freed
  src/graph/serializers/graphcontext_type.c
  src/graph/serializers/serialize_graph.c
  src/graph/serializers/serialize_store.c
Labels: bug

#230 iterative DFS for finding variable length paths
  src/algorithms/all_paths.c
  src/algorithms/all_paths.h
  src/algorithms/path.c
  src/algorithms/path.h
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_cond_var_len_traverse.h
  src/parser/grammar.c
  src/parser/grammar.y
  tests/unit/test_all_paths.cpp
Labels: enhancement

#231 explain response with: 'key doesn't contains a graph object.' when tr…
  src/commands/cmd_explain.c
Labels: bug

#244 support '*' within RETURN clause
  demo/imdb/imdb_queries.py
  src/parser/ast_arithmetic_expression.c
  src/parser/clauses/match.c
  src/parser/clauses/return.c
  src/parser/clauses/return.h
  src/parser/grammar.c
  src/parser/grammar.y
  src/query_executor.c
  src/util/triemap/triemap_type.c
  src/util/triemap/triemap_type.h
Labels: enhancement

#236 Add TYPE function to match LABELS
  demo/social/social_queries.py
  docs/commands.md
  src/arithmetic/algebraic_expression.c
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/graph/serializers/serialize_graph.c
  src/index/index.c
  src/parser/ast_arithmetic_expression.c
  src/parser/grammar.c
  src/parser/grammar.y
  src/parser/lex.yy.c
  src/query_executor.c
  src/resultset/resultset_record.c
  src/value.c
  src/value.h
  tests/flow/test_social.py
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_arithmetic_expression.cpp
  tests/unit/test_filter_tree.cpp
  tests/unit/test_index.cpp
  tests/unit/test_resultset_record.cpp
  tests/unit/test_value.cpp
Labels: enhancement

#247 initial support for unwind clause
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_unwind.c
  src/execution_plan/ops/op_unwind.h
  src/execution_plan/ops/ops.h
  src/parser/ast.c
  src/parser/ast.h
  src/parser/ast_arithmetic_expression.c
  src/parser/clauses/clauses.h
  src/parser/clauses/match.c
  src/parser/clauses/match.h
  src/parser/clauses/unwind.c
  src/parser/clauses/unwind.h
  src/parser/grammar.c
  src/parser/grammar.h
  src/parser/grammar.y
  src/parser/lex.yy.c
  src/parser/lexer.l
  src/query_executor.c
Labels: enhancement

#248 min,max support for mixed types, unwind with skip and limit
  src/arithmetic/agg_funcs.c
  src/graph/entities/graph_entity.c
  src/graph/graph.c
  src/parser/grammar.c
  src/parser/grammar.y
  src/value.c
  tests/tck/features/Aggregation.feature
  tests/tck/features/ReturnAcceptance.feature
  tests/tck/features/steps/Steps.py
  tests/tck/utils/assertions.py
  tests/tck/utils/graphs.py
Labels: bug, enhancement

#258 multiple CREATE clauses, enable TCK
  src/parser/grammar.c
  src/parser/grammar.y
  tests/Makefile
  tests/flow/test_multi_pattern.py
  tests/tck/features/AggregationAcceptance.feature
  tests/tck/features/ReturnAcceptance.feature
  tests/tck/features/StartingPointAcceptance.feature
Labels: enhancement

#260 Respect Cypher specifications for orderability and comparability
  src/arithmetic/agg_funcs.c
  src/filter_tree/filter_tree.c
  src/resultset/resultset.c
  src/resultset/resultset_record.c
  src/value.c
  src/value.h
  tests/flow/test_value_comparisons.py
Labels: bug

#262 entity returned from datablock should have its internals cleared
  src/graph/graph.c
Labels: bug

#264 Loaded triemap strings are not guaranteed space for a null terminator
  src/graph/serializers/serialize_store.c
Labels: bug

#252 initial support for multiple MATCH clauses
  src/parser/grammar.c
  src/parser/grammar.y
  tests/flow/test_multi_pattern.py
Labels: cypher, enhancement

#270 queried the wrong operand to see if an algebric expression is reversed
  src/execution_plan/ops/op_conditional_traverse.c
  tests/flow/test_reversed_patterns.py
Labels: bug

#271 Install the m4 dependency for GraphBLAS in Docker
  Dockerfile
Labels: bug
