Repository RedisGraph/RedisGraph, pull requests merged in 2019-08, with the labels that each got.

#576 Remove result set dependency on ExecutionPlan projections
  src/execution_plan/execution_plan.c
  src/resultset/formatters/resultset_formatter.h
  src/resultset/formatters/resultset_replycompact.c
  src/resultset/formatters/resultset_replycompact.h
  src/resultset/formatters/resultset_replynop.c
  src/resultset/formatters/resultset_replynop.h
  src/resultset/formatters/resultset_replyverbose.c
  src/resultset/formatters/resultset_replyverbose.h
  src/resultset/resultset.c
  src/resultset/resultset.h
  tests/flow/test_with_clause.py
Labels: bug

#582 support contains operator
  docs/commands.md
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast_build_filter_tree.c
  src/ast/ast_shared.c
  src/ast/ast_shared.h
  src/ast/cypher_whitelist.c
  src/filter_tree/filter_tree.c
  src/value.h
  tests/flow/Makefile
  tests/tck/Makefile
  tests/tck/features/StartsWithAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: cypher, enhancement

#586 case simple form
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast_mapping.c
  src/ast/cypher_whitelist.c
  tests/unit/test_arithmetic_expression.cpp
Labels: cypher, enhancement

#587 ternary operators
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast_build_filter_tree.c
  src/ast/ast_shared.c
  src/ast/ast_shared.h
  src/ast/ast_validations.c
  src/ast/cypher_whitelist.c
  src/execution_plan/execution_plan.c
  tests/tck/features/ComparisonOperatorAcceptance.feature
  tests/tck/features/TernaryLogicAcceptance.feature
  tests/unit/test_arithmetic_expression.cpp
Labels: cypher, enhancement

#583 Introduce NOT operator
  docs/commands.md
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/arithmetic/funcs.h
  src/ast/ast_build_ar_exp.c
  src/ast/ast_build_ar_exp.h
  src/ast/ast_build_filter_tree.c
  src/ast/ast_build_op_contexts.c
  src/ast/ast_validations.c
  src/execution_plan/execution_plan.c
  src/execution_plan/optimizations/seek_by_id.c
  src/filter_tree/filter_tree.c
  src/filter_tree/filter_tree.h
  tests/tck/features/StartsWithAcceptance.feature
  tests/unit/test_aggregate_functions.cpp
  tests/unit/test_filter_tree.cpp
Labels: cypher

#596 node incoming outgoing degree
  docs/commands.md
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/funcs.h
  src/graph/graph.c
  tests/flow/test_social.py
Labels: enhancement

#598 Fix function names for existence and aggregation checks
  src/ast/ast.c
  src/ast/ast_validations.c
Labels: bug

#594 Support dynamic inline properties for CREATE and MERGE patterns
  src/ast/ast_build_filter_tree.c
  src/ast/ast_build_op_contexts.c
  src/ast/ast_build_op_contexts.h
  src/ast/ast_shared.c
  src/ast/ast_shared.h
  src/ast/ast_validations.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_create.h
  src/execution_plan/ops/op_merge.c
  src/graph/entities/graph_entity.h
  src/graph/query_graph.c
  src/graph/query_graph.h
  src/record/record_context.c
  tests/flow/test_graph_create.py
  tests/flow/test_graph_merge.py
  tests/tck/features/VarLengthAcceptance.feature
Labels: enhancement

#591 Emit validation error when an alias refers to both nodes and edges
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_validations.c
  src/execution_plan/execution_plan.c
Labels: bug

#600 Sivalue memory safety
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast_build_ar_exp.c
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_project.c
  src/execution_plan/record.c
  src/execution_plan/record.h
  src/graph/entities/graph_entity.c
  src/index/index.c
  src/value.c
  src/value.h
  tests/unit/test_arithmetic_expression.cpp
Labels: bug

#606 Fix Record ID of edges held in ExpandInto op
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_expand_into.h
  src/execution_plan/optimizations/reduce_traversal.c
  src/filter_tree/filter_tree.c
Labels: bug

#607 All ops NULL-set variables in their free routines
  src/execution_plan/ops/op_apply.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_merge.c
Labels: bug

#609 added strip in make to reduce module size
  src/Makefile
Labels: bug

#608 Bgsave
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/graph/serializers/encoder/encode_graphcontext.c
  src/graph/serializers/graphcontext_type.c
  src/module.c
Labels: bug

#604 Client documentation updates
  docs/client_spec.md
  docs/clients.md
  docs/index.md
  docs/result_structure.md
  mkdocs.yml
Labels: Documentation
