Repository RedisGraph/RedisGraph, pull requests merged in 2019-09, with the labels that each got.

#603 Fix regression in DropIndex
  deps/RediSearch/cmake/redisearch_cflags.cmake
  deps/RediSearch/docker/Dockerfile
  deps/RediSearch/rmtest.config.default
  deps/RediSearch/sizes
  deps/RediSearch/src/aggregate/aggregate_exec.c
  deps/RediSearch/src/aggregate/aggregate_plan.c
  deps/RediSearch/src/aggregate/aggregate_plan.h
  deps/RediSearch/src/aggregate/aggregate_request.c
  deps/RediSearch/src/config.c
  deps/RediSearch/src/config.h
  deps/RediSearch/src/document.c
  deps/RediSearch/src/fork_gc.c
  deps/RediSearch/src/fork_gc.h
  deps/RediSearch/src/gc.h
  deps/RediSearch/src/indexer.c
  deps/RediSearch/src/indexer.h
  deps/RediSearch/src/pytest/CMakeLists.txt
  deps/RediSearch/src/pytest/test.py
  deps/RediSearch/src/pytest/test_aggregate.py
  deps/RediSearch/src/pytest/test_gc.py
  deps/RediSearch/src/redisearch_api.c
  deps/RediSearch/src/redismodule.h
  deps/RediSearch/src/rmutil/test_args
  deps/RediSearch/src/rmutil/test_cmdparse
  deps/RediSearch/src/rmutil/test_heap
  deps/RediSearch/src/rmutil/test_periodic
  deps/RediSearch/src/rmutil/test_priority_queue
  deps/RediSearch/src/rmutil/test_vector
  deps/RediSearch/src/trie/trie.c
  src/redismodule.h
Labels: bug

#615 unit test dont mind 'leaking' fake context as it now depends on modul…
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_index.cpp
Labels: bug

#623 Issue617
  src/arithmetic/agg_funcs.c
  src/arithmetic/arithmetic_expression.c
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_sort.c
  src/execution_plan/ops/op_value_hash_join.c
  src/filter_tree/filter_tree.c
  src/value.c
  src/value.h
  tests/flow/test_value_comparisons.py
  tests/tck/features/Comparability.feature
  tests/tck/features/OrderByAcceptance.feature
Labels: enhancement

#635 Disallow potentially unhandled MERGE queries
  src/ast/ast_validations.c
  tests/flow/test_graph_merge.py
  tests/tck/features/MergeRelationshipAcceptance.feature
Labels: bug

#643 Iterative execution plan
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/execution_plan_modify.c
  src/execution_plan/ops/op_results.c
  src/execution_plan/ops/op_results.h
  src/execution_plan/optimizations/optimizations.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/relocate_op.c
  src/execution_plan/optimizations/relocate_op.h
  src/resultset/resultset.h
  tests/unit/test_algebraic_expression.cpp
Labels: enhancement

#654 Add instructions for updating OS X compilers
  README.md
  docs/index.md
Labels: Documentation

#655 Fix referenced alias validations for WITH and WHERE clauses
  src/ast/ast_validations.c
  tests/flow/test_query_validation.py
Labels: bug

#657 used wrong semiring for mxm
  src/arithmetic/algebraic_expression.c
Labels: bug

#663 Set datatype
  src/datatypes/array.c
  src/datatypes/array.h
  src/datatypes/set.c
  src/datatypes/set.h
  src/value.c
  src/value.h
  tests/unit/Makefile
  tests/unit/test_value.cpp
Labels: enhancement

#660 Fix transpose logic for traversals with non-scan children
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_conditional_traverse.c
  tests/flow/test_relation_patterns.py
Labels: bug

#662 support AOF
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/module.c
Labels: enhancement

#668 Pagerank
  demo/social/social_queries.py
  docs/commands.md
  src/algorithms/pagerank.c
  src/algorithms/pagerank.h
  src/procedures/proc_pagerank.c
  src/procedures/proc_pagerank.h
  src/procedures/procedure.c
  src/procedures/procedures.h
  tests/flow/test_pagerank.py
  tests/flow/test_social.py
  tests/unit/test_pagerank.cpp
Labels: cypher, enhancement
