Repository RedisGraph/RedisGraph, pull requests merged in 2019-11, with the labels that each got.

#720 Validate function calls in WITH and CREATE clauses
  src/ast/ast_validations.c
Labels: bug

#728 map set expression right hand side
  src/ast/ast_build_reference_map.c
  tests/unit/test_referenced_entities.cpp
Labels: bug

#730 Op join
  docs/commands.md
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_validations.c
  src/ast/cypher_whitelist.c
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan_modify.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_join.c
  src/execution_plan/ops/op_join.h
  src/execution_plan/ops/op_limit.c
  src/execution_plan/ops/op_results.h
  src/execution_plan/ops/ops.h
  tests/tck/features/MiscellaneousErrorAcceptance.feature
  tests/tck/features/UnionAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: cypher

#732 detect cycles in graph
  src/GraphBLASExt/GxB_Delete.c
  src/GraphBLASExt/GxB_Delete.h
  src/algorithms/algorithms.h
  src/algorithms/detect_cycle.c
  src/algorithms/detect_cycle.h
  src/graph/entities/qg_node.h
  src/graph/query_graph.c
  src/graph/query_graph.h
  tests/unit/test_detect_cycle.cpp
Labels: bug

#735 Index string ownership
  src/execution_plan/optimizations/utilize_indices.c
  tests/flow/test_index_scans.py
Labels: bug

#734 Fix access of uninitialized GrB_Info
  src/algorithms/detect_cycle.c
Labels: bug

#736 generate algebraic expression from cyclic graph
  src/algorithms/algorithms.h
  src/algorithms/detect_cycle.c
  src/algorithms/dfs.c
  src/algorithms/dfs.h
  src/algorithms/longest_path.c
  src/algorithms/longest_path.h
  src/arithmetic/algebraic_expression.c
  src/module.c
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_detect_cycle.cpp
  tests/unit/test_dfs.cpp
Labels: bug

#755 Fix outdated lines of Cypher Coverage documentation
  docs/cypher_support.md
Labels: Documentation

#758 make sure all return clauses are annotated
  src/ast/enrichment/annotate_projected_named_paths.c
  src/value.c
  tests/flow/test_union.py
Labels: bug

#765 last op in sub execution-plan doesn't nesseceraly has to be projectio…
  src/execution_plan/execution_plan.c
  tests/flow/test_union.py
Labels: bug

#766 Datablock delete item thread-safe, update graph writer lock before un…
  src/graph/graph.c
  src/util/datablock/datablock.c
  src/util/datablock/datablock.h
  tests/flow/test_stress.py
Labels: bug
