Repository RedisGraph/RedisGraph, pull requests merged in 2019-04, with the labels that each got.

#431 delay matrix retrieval, avoid performing matrix sync when possible
  src/arithmetic/algebraic_expression.c
  src/graph/entities/edge.c
  src/graph/entities/edge.h
  src/graph/graph.h
  src/graph/query_graph.c
Labels: enhancement

#439 node count 0 when label does not exists
  src/execution_plan/optimizations/reduce_count.c
Labels: bug

#442 node by id seek execution plan operation
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_node_by_id_seek.c
  src/execution_plan/ops/op_node_by_id_seek.h
  src/execution_plan/ops/ops.h
  src/execution_plan/optimizations/optimizations.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/seek_by_id.c
  src/execution_plan/optimizations/seek_by_id.h
  src/util/datablock/datablock_iterator.h
  tests/flow/test_node_by_id.py
Labels: enhancement

#453 function invocation without arguments
  docs/cypher_support.md
  src/parser/grammar.c
  src/parser/grammar.y
Labels: cypher

#452 multiple edges of the same type R connecting nodes A and B
  demo/bulk_insert/resources/Country.csv
  demo/bulk_insert/resources/VISITED.csv
  demo/social/resources/countries.csv
  demo/social/resources/visits.csv
  demo/social/social_queries.py
  docs/cypher_support.md
  docs/known_limitations.md
  src/algorithms/all_paths.c
  src/graph/graph.c
  src/graph/graph.h
  src/graph/serializers/graphcontext_type.h
  src/graph/serializers/serialize_graph.c
  tests/flow/test_bulk_insertion.py
  tests/flow/test_multiple_edges.py
  tests/flow/test_persistency.py
  tests/flow/test_social.py
Labels: enhancement

#458 Memory leaks
  src/arithmetic/algebraic_expression.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_filter.c
  src/execution_plan/optimizations/reduce_filters.c
  src/filter_tree/filter_tree.c
  src/graph/query_graph.c
  src/parser/ast.c
  src/parser/ast_common.c
  src/parser/ast_common.h
  src/parser/clauses/match.c
  src/parser/clauses/return.c
  src/parser/clauses/return.h
  src/parser/clauses/where.c
  src/parser/grammar.c
  src/parser/grammar.y
  src/query_executor.c
  tests/unit/test_filter_tree.cpp
Labels: bug

#459 Delay node matrix retrieval up to algebraic expression construction, …
  src/algorithms/path.c
  src/arithmetic/algebraic_expression.c
  src/execution_plan/ops/op_node_by_label_scan.c
  src/graph/entities/edge.c
  src/graph/entities/edge.h
  src/graph/entities/node.c
  src/graph/entities/node.h
  src/graph/graph.c
  src/graph/graph.h
  src/graph/query_graph.c
  src/index/index.c
  tests/unit/test_algebraic_expression.cpp
Labels: enhancement

#462 do not apply count potimization when counting entity property
  src/arithmetic/arithmetic_expression.c
  src/execution_plan/optimizations/reduce_count.c
Labels: bug

#470 #469 Fix double free of Record in variable length traverse
  src/execution_plan/ops/op_cond_var_len_traverse.c
Labels: bug

#472 quick return if there are no relations to traverse
  src/execution_plan/ops/op_cond_var_len_traverse.c
Labels: bug
