Repository RedisGraph/RedisGraph, pull requests merged in 2019-07, with the labels that each got.

#546 make sure removed operand is a label matrix when creating a labelscan op
  src/execution_plan/execution_plan.c
Labels: bug

#550 optimize cartesian product by reducing to join
  demo/imdb/imdb_queries.py
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_value_hash_join.c
  src/execution_plan/ops/op_value_hash_join.h
  src/execution_plan/ops/ops.h
  src/execution_plan/optimizations/apply_join.c
  src/execution_plan/optimizations/apply_join.h
  src/execution_plan/optimizations/optimizations.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/record.c
  src/execution_plan/record.h
  src/value.c
  tests/flow/test_imdb.py
  tests/tck/features/MatchAcceptance2.feature
  tests/tck/features/VarLengthAcceptance.feature
Labels: enhancement

#545 opbase consume function
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_cartesian_product.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_distinct.c
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_filter.c
  src/execution_plan/ops/op_limit.c
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_procedure_call.c
  src/execution_plan/ops/op_project.c
  src/execution_plan/ops/op_results.c
  src/execution_plan/ops/op_skip.c
  src/execution_plan/ops/op_sort.c
  src/execution_plan/ops/op_update.c
Labels: enhancement

#555 join prefer caching filtered branch
  src/execution_plan/ops/op_value_hash_join.c
  src/execution_plan/optimizations/apply_join.c
Labels: enhancement

#567 Tck updates
  tests/tck/features/Aggregation.feature
  tests/tck/features/AggregationAcceptance.feature
  tests/tck/features/Comparability.feature
  tests/tck/features/ComparisonOperatorAcceptance.feature
  tests/tck/features/Create.feature
  tests/tck/features/CreateAcceptance.feature
  tests/tck/features/DeleteAcceptance.feature
  tests/tck/features/EqualsAcceptance.feature
  tests/tck/features/FunctionsAcceptance.feature
  tests/tck/features/LargeIntegerEquality.feature
  tests/tck/features/MatchAcceptance.feature
  tests/tck/features/MatchAcceptance2.feature
  tests/tck/features/MergeIntoAcceptance.feature
  tests/tck/features/OrderByAcceptance.feature
  tests/tck/features/StartingPointAcceptance.feature
  tests/tck/features/VarLengthAcceptance.feature
  tests/tck/features/WithAcceptance.feature
  tests/tck/features/steps/Steps.py
  tests/tck/utils/assertions.py
Labels: enhancement

#571 Parse queries in thread
  src/ast/cypher_whitelist.c
  src/ast/cypher_whitelist.h
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_context.c
  src/commands/cmd_context.h
  src/commands/cmd_delete.c
  src/commands/cmd_explain.c
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/module.c
  src/redismodule.h
Labels: enhancement

#572 Update documentation to reflect recent feature additions
  docs/commands.md
  docs/cypher_support.md
  docs/index.md
  docs/known_limitations.md
  docs/result_structure.md
Labels: Documentation
