Repository RedisGraph/RedisGraph, pull requests merged in 2019-12, with the labels that each got.

#773 changed bulk edge delete
  src/graph/graph.c
  tests/flow/test_graph_deletion.py
Labels: enhancement

#786 procedure arguments are evaluated from arithmetic expressions
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_procedure_call.c
  src/execution_plan/ops/op_procedure_call.h
  src/procedures/proc_ctx.h
  src/procedures/proc_fulltext_create_index.c
  src/procedures/proc_fulltext_drop_index.c
  src/procedures/proc_fulltext_query.c
  src/procedures/proc_labels.c
  src/procedures/proc_pagerank.c
  src/procedures/proc_property_keys.c
  src/procedures/proc_relations.c
  src/procedures/procedure.c
  src/procedures/procedure.h
  src/value.h
  tests/flow/test_procedures.py
Labels: cypher, enhancement

#789 aggregate static value where there's no previous data coming in
  src/execution_plan/ops/op_aggregate.c
  tests/flow/test_function_calls.py
Labels: bug, cypher

#791 merge create when performing distinction, should take into account me…
  src/execution_plan/ops/op_merge_create.c
  tests/flow/test_graph_merge.py
Labels: bug

#794 treat missing relationship edge count as 0
  src/execution_plan/optimizations/reduce_count.c
  tests/flow/test_optimizations_plan.py
Labels: bug

#785 Memory leak patches
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_build_op_contexts.c
  src/ast/enrichment/annotate_entities.c
  src/ast/enrichment/annotate_params.c
  src/ast/enrichment/annotate_project_all.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_cond_var_len_traverse.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_expand_into.h
  src/execution_plan/ops/op_index_scan.c
  src/execution_plan/ops/op_node_by_id_seek.c
  src/execution_plan/ops/op_node_by_id_seek.h
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/shared/print_functions.c
  src/execution_plan/ops/shared/print_functions.h
  src/execution_plan/optimizations/reduce_traversal.c
  src/execution_plan/optimizations/seek_by_id.c
  src/execution_plan/optimizations/traverse_order.c
  src/execution_plan/optimizations/traverse_order.h
  src/graph/query_graph.c
  src/graph/query_graph.h
  src/query_ctx.c
  src/util/strcmp.h
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_traversal_ordering.cpp
Labels: bug

#797 range arg validation
  src/arithmetic/list_funcs/list_funcs.c
  tests/tck/features/SemanticErrorAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: bug, cypher

#790 emit error when an expression contains nested calls of aggregation fu…
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast_build_ar_exp.c
  src/commands/cmd_explain.c
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_aggregate.c
  src/query_ctx.c
  tests/flow/test_function_calls.py
  tests/tck/features/AggregationAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: bug, cypher

#796 Delete elements verification
  docs/commands.md
  docs/cypher_support.md
  src/arithmetic/numeric_funcs/numeric_funcs.c
  src/ast/ast_build_op_contexts.c
  src/ast/ast_build_op_contexts.h
  src/ast/ast_build_reference_map.c
  src/ast/ast_validations.c
  src/ast/enrichment/annotate_projected_named_paths.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_delete.h
  src/execution_plan/ops/op_unwind.c
  tests/flow/test_graph_deletion.py
  tests/tck/features/AggregationAcceptance.feature
  tests/tck/features/EqualsAcceptance.feature
  tests/unit/test_arithmetic_expression.cpp
Labels: bug, cypher

#805 allow hashing of record with unknown entries
  src/execution_plan/record.c
  tests/tck/features/AggregationAcceptance.feature
Labels: bug

#806 no support for optional match
  src/ast/ast_validations.c
  tests/tck/features/DeleteAcceptance.feature
  tests/tck/features/MatchAcceptance2.feature
  tests/tck/features/NullAcceptance.feature
  tests/tck/features/OptionalMatchAcceptance.feature
  tests/tck/features/VarLengthAcceptance.feature
Labels: bug

#807 annotate named paths within match clause
  src/ast/enrichment/annotate_projected_named_paths.c
  tests/tck/features/MatchAcceptance.feature
Labels: bug

#809 Add tck error handlers
  tests/tck/features/MergeRelationshipAcceptance.feature
  tests/tck/features/SkipLimitAcceptance.feature
  tests/tck/features/SyntaxErrorAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: enhancement

#808 Validate function calls in UNWIND expressions
  src/ast/ast_validations.c
  tests/tck/features/FunctionsAcceptance.feature
  tests/tck/features/UnwindAcceptance.feature
Labels: bug

#810 Validate identifiers in ON MATCH and ON CREATE actions
  src/ast/ast_validations.c
  tests/tck/features/SemanticErrorAcceptance.feature
Labels: bug

#804 validate filter tree structure, raise a compile time exception if inv…
  src/ast/ast_build_filter_tree.c
  src/execution_plan/optimizations/reduce_filters.c
  src/execution_plan/optimizations/utilize_indices.c
  src/filter_tree/filter_tree.c
  src/filter_tree/filter_tree.h
  tests/unit/test_filter_tree.cpp
Labels: bug

#815 Validate that WITH projections are identifiers or aliased
  src/ast/ast_validations.c
  tests/tck/features/MiscellaneousErrorAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: bug

#821 Improve bound variable checking in CREATE clauses
  src/ast/ast_validations.c
  tests/flow/test_pagerank.py
  tests/flow/test_query_validation.py
  tests/tck/features/SemanticErrorAcceptance.feature
Labels: bug

#811 Properly handle zero-hop traversals
  src/execution_plan/execution_plan.c
  tests/tck/features/VarLengthAcceptance.feature
Labels: bug

#824 Emit a compile-time error when failing to parse AST numeric nodes
  src/ast/ast_build_ar_exp.c
  tests/tck/features/SyntaxErrorAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: bug

#826 Fix validation on redeclaring edges aliases in MERGE clauses
  src/ast/ast_validations.c
  tests/tck/features/SemanticErrorAcceptance.feature
Labels: bug

#813 Filter placement updates
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/execution_plan_modify.c
  tests/flow/test_with_clause.py
  tests/tck/features/WithAcceptance.feature
Labels: bug

#844 op_unwind handel double free
  src/execution_plan/ops/op_unwind.c
Labels: bug

#843 avoid creating duplications when aliasing modifiers
  src/execution_plan/ops/op.c
Labels: bug

#842 update algebraic expression operands dim as a result of a prev write
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_all_node_scan.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/shared/create_functions.c
  src/graph/graph.c
  tests/flow/test_graph_merge.py
Labels: bug

#847 Add support for long values in bulk loader
  src/bulk_insert/bulk_insert.c
Labels: enhancement

#837 Algebraic tree
  src/Makefile
  src/arithmetic/algebraic_expression.c
  src/arithmetic/algebraic_expression.h
  src/arithmetic/algebraic_expression/algebraic_expression.c
  src/arithmetic/algebraic_expression/algebraic_expression_construction.c
  src/arithmetic/algebraic_expression/algebraic_expression_debug.c
  src/arithmetic/algebraic_expression/algebraic_expression_eval.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  src/arithmetic/algebraic_expression/algebraic_expression_transpose.c
  src/arithmetic/algebraic_expression/utils.c
  src/arithmetic/algebraic_expression/utils.h
  src/ast/ast_validations.c
  src/commands/cmd_explain.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_cond_var_len_traverse.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_expand_into.h
  src/execution_plan/ops/shared/print_functions.c
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/reduce_traversal.c
  src/execution_plan/optimizations/traverse_order.c
  src/graph/entities/qg_edge.c
  src/graph/entities/qg_edge.h
  src/graph/graph.c
  src/graph/query_graph.c
  tests/flow/test_graph_merge.py
  tests/flow/test_params.py
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_traversal_ordering.cpp
Labels: enhancement
