Repository RedisGraph/RedisGraph, pull requests merged in 2019-10, with the labels that each got.

#658 count distinct aggregation function
  src/arithmetic/agg_ctx.h
  src/arithmetic/agg_funcs.c
  src/arithmetic/agg_funcs.h
  src/arithmetic/aggregate.c
  src/arithmetic/aggregate.h
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/arithmetic/repository.c
  src/arithmetic/repository.h
  src/ast/ast_build_ar_exp.c
  src/execution_plan/optimizations/reduce_count.c
  src/value.c
  tests/flow/test_distinct.py
  tests/tck/features/Aggregation.feature
  tests/tck/features/AggregationAcceptance.feature
  tests/unit/test_aggregate_functions.cpp
Labels: cypher, enhancement

#672 Don't access undefined CondTraverse members
  src/execution_plan/optimizations/reduce_count.c
  tests/flow/test_optimizations_plan.py
Labels: bug

#683 must not free execution plan record-map before freeing individual ope…
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_cartesian_product.c
Labels: bug

#689 Fix entity resolution in Value Hash Join insertions
  src/execution_plan/optimizations/apply_join.c
  tests/flow/test_optimizations_plan.py
Labels: bug

#692 build filter tree applied to the with clause
  src/ast/ast_build_filter_tree.c
  tests/flow/test_with_clause.py
Labels: enhancement

#690 restrict forked process to a single GraphBLAS thread
  src/module.c
Labels: bug

#700 Var len bugfix
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/graph/entities/edge.c
  src/graph/graph.c
  tests/flow/test_variable_length_traversals.py
Labels: bug

#707 Update AST in QueryCtx after segment construction
  src/execution_plan/execution_plan.c
Labels: bug
