Repository RedisGraph/RedisGraph, pull requests merged in 2019-01, with the labels that each got.

#305 support MERGE SET
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_merge.h
  src/execution_plan/ops/op_update.c
  src/parser/ast.c
  src/parser/clauses/create.c
  src/parser/clauses/match.c
  src/parser/clauses/merge.c
  src/parser/clauses/merge.h
  src/parser/grammar.c
  src/parser/grammar.y
  tests/flow/test_graph_merge.py
Labels: enhancement

#308 granular locking
  src/Makefile
  src/commands/cmd_bulk_insert.h
  src/commands/cmd_delete.c
  src/commands/cmd_delete.h
  src/commands/cmd_explain.c
  src/commands/cmd_explain.h
  src/commands/cmd_query.c
  src/commands/cmd_query.h
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_produce_results.c
  src/execution_plan/ops/op_produce_results.h
  src/execution_plan/ops/op_update.c
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graphcontext.c
  src/graph/serializers/graphcontext_type.c
  src/module.c
  src/query_executor.h
  src/redismodule.h
  src/util/datablock/datablock_iterator.c
Labels: enhancement

#310 Save the edge count from matrix rather than datablock values
  src/graph/serializers/serialize_graph.c
  tests/flow/test_persistency.py
Labels: bug

#311 unused arg within user defined semiring, cleaner build output, faster …
  deps/GraphBLAS/Include/GraphBLAS.h
  deps/GraphBLAS/Source/all_user_objects.c
  deps/GraphBLAS/User/rg_structured_bool.m4
  src/Makefile
  tests/unit/Makefile
Labels: enhancement

#309 traverse multiple nodes concurrently
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
Labels: enhancement

#319 Use Redis memory manager to store graph name
  src/commands/cmd_query.c
Labels: bug

#322 Store graph name string outside of Redis context
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_explain.c
  src/commands/cmd_query.c
  src/commands/cmd_query.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
Labels: bug

#324 Don't install or check for OpenMP
  Dockerfile
  src/Makefile
  tests/unit/Makefile
Labels: enhancement

#327 allow mixing MATCH CREATE and RETURN clauses
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_aggregate.h
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_create.h
  src/execution_plan/ops/op_project.c
  src/execution_plan/ops/op_project.h
  src/parser/ast.c
  src/parser/ast_common.h
  src/parser/clauses/create.c
  src/parser/clauses/create.h
  src/parser/clauses/match.c
  src/parser/clauses/merge.c
  src/query_executor.c
  src/query_executor.h
  src/resultset/resultset.c
  src/resultset/resultset.h
  tests/flow/test_graph_deletion.py
  tests/flow/test_graph_merge.py
  tests/flow/test_multi_pattern.py
Labels: cypher, enhancement

#330 addition perform string concat
  src/arithmetic/arithmetic_expression.c
  src/execution_plan/optimizations/utilize_indices.c
  src/graph/graphcontext.c
  src/value.h
  tests/unit/test_arithmetic_expression.cpp
Labels: cypher, enhancement

#334 reverse match pattern to reduce number of matrix transpose
  demo/imdb/imdb_queries.py
  demo/social/social_queries.py
  src/parser/ast_common.c
  src/parser/ast_common.h
  src/query_executor.c
  tests/flow/base.py
  tests/flow/reversepattern/__init__.py
  tests/flow/test_imdb.py
  tests/flow/test_social.py
Labels: enhancement

#341 Type-safe numeric addition
  src/arithmetic/arithmetic_expression.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/value.c
  src/value.h
Labels: bug
