Repository RedisGraph/RedisGraph, pull requests merged in 2019-03, with the labels that each got.

#382 With clause additional validations
  src/arithmetic/arithmetic_expression.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_limit.c
  src/execution_plan/ops/op_limit.h
  src/execution_plan/ops/op_project.c
  src/execution_plan/ops/op_results.c
  src/execution_plan/ops/op_results.h
  src/execution_plan/ops/op_skip.c
  src/execution_plan/ops/op_skip.h
  src/execution_plan/ops/op_sort.h
  src/execution_plan/ops/op_unwind.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_update.h
  src/execution_plan/optimizations/relocate_op.c
  src/execution_plan/optimizations/relocate_op.h
  src/execution_plan/record.c
  src/graph/query_graph.c
  src/grouping/group.c
  src/parser/ast.c
  src/parser/clauses/order.c
  src/parser/clauses/order.h
  src/parser/clauses/with.c
  src/parser/clauses/with.h
  tests/flow/test_with_clause.py
Labels: enhancement

#383 remove graph entity property when it is set to null, introduce exists…
  docs/commands.md
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/execution_plan/ops/op_update.c
  src/graph/entities/graph_entity.c
  tests/flow/test_graph_deletion.py
  tests/unit/test_arithmetic_expression.cpp
Labels: bug, cypher, enhancement

#353 expand into operation
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_expand_into.h
  src/execution_plan/ops/ops.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
Labels: cypher, enhancement

#393 discard distinct when performing aggregation
  src/execution_plan/optimizations/optimizations.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/optimizer.h
  src/execution_plan/optimizations/reduce_distinct.c
  src/execution_plan/optimizations/reduce_distinct.h
  tests/flow/redis_base.py
  tests/flow/test_distinct.py
Labels: enhancement

#395 compile on alpine
  src/parser/grammar.c
  src/parser/grammar.y
  src/parser/lex.yy.c
  src/util/datablock/datablock.c
  src/util/datablock/datablock.h
  src/util/datablock/datablock_iterator.h
  src/util/triemap/triemap.h
  src/value.h
Labels: bug, enhancement

#399 Transpose algebraic operand only once
  src/arithmetic/algebraic_expression.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
Labels: enhancement

#400 Procedure call
  src/Makefile
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_procedure_call.c
  src/execution_plan/ops/op_procedure_call.h
  src/execution_plan/ops/ops.h
  src/module.c
  src/parser/ast.c
  src/parser/ast.h
  src/parser/clauses/call.c
  src/parser/clauses/call.h
  src/parser/clauses/clauses.h
  src/parser/grammar.c
  src/parser/grammar.h
  src/parser/grammar.y
  src/parser/lex.yy.c
  src/parser/lexer.l
  src/procedures/fulltext_create_index.c
  src/procedures/fulltext_create_index.h
  src/procedures/fulltext_query.c
  src/procedures/fulltext_query.h
  src/procedures/proc_ctx.h
  src/procedures/procedure.c
  src/procedures/procedure.h
  src/procedures/procedures.h
  src/query_executor.c
  tests/flow/test_procedures.py
Labels: cypher, enhancement

#339 Full entity returns
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/bulk_insert/bulk_insert.c
  src/commands/cmd_explain.c
  src/commands/cmd_query.c
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_create.h
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_delete.h
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_merge.h
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/op_node_by_label_scan.h
  src/execution_plan/ops/op_project.c
  src/execution_plan/ops/op_results.c
  src/execution_plan/ops/op_results.h
  src/execution_plan/ops/op_sort.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_update.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/optimizer.h
  src/execution_plan/optimizations/utilize_indices.c
  src/execution_plan/optimizations/utilize_indices.h
  src/execution_plan/record.c
  src/execution_plan/record.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/graph/serializers/graphcontext_type.c
  src/graph/serializers/graphcontext_type.h
  src/graph/serializers/serialize_graph.c
  src/graph/serializers/serialize_graph.h
  src/graph/serializers/serialize_schema.c
  src/graph/serializers/serialize_schema.h
  src/index/index.c
  src/parser/ast.c
  src/parser/ast_arithmetic_expression.h
  src/parser/clauses/return.c
  src/parser/clauses/return.h
  src/parser/grammar.c
  src/parser/grammar.y
  src/parser/lex.yy.c
  src/query_executor.c
  src/query_executor.h
  src/resultset/resultset.c
  src/resultset/resultset.h
  src/resultset/resultset_formatters.h
  src/resultset/resultset_replycompact.c
  src/resultset/resultset_replyverbose.c
  src/schema/schema.c
  src/schema/schema.h
  src/value.c
  src/value.h
  tests/flow/test_results.py
  tests/unit/test_filter_tree.cpp
Labels: enhancement

#392 Lexer elides escape characters in string creation
  src/parser/lex.yy.c
  src/parser/lexer.l
  tests/flow/test_query_validation.py
Labels: enhancement

#406 Create fulltext index
  demo/imdb/imdb_queries.py
  src/execution_plan/execution_plan.c
  src/module.c
  src/parser/ast.c
  src/procedures/fulltext_create_index.c
  src/procedures/fulltext_query.c
  src/redisearch_api.h
  src/schema/schema.c
  src/schema/schema.h
  tests/flow/test_imdb.py
Labels: cypher, enhancement

#408 Include column's entity type in compact headers
  src/commands/cmd_query.c
  src/parser/ast.c
  src/parser/ast.h
  src/resultset/resultset.c
  src/resultset/resultset.h
  src/resultset/resultset_formatters.h
  src/resultset/resultset_replycompact.c
  src/resultset/resultset_replyverbose.c
Labels: enhancement

#424 Remove deny-script flag from GRAPH commands
  src/module.c
Labels: enhancement

#422 optimize node count
  demo/imdb/imdb_queries.py
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/execution_plan/optimizations/optimizations.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/reduce_count.c
  src/execution_plan/optimizations/reduce_count.h
  src/graph/graph.c
  src/graph/graph.h
  tests/flow/test_imdb.py
Labels: enhancement
