Repository RedisGraph/RedisGraph, pull requests merged in 2019-06, with the labels that each got.

#508 Better handling for entity creation
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_create.h
  tests/flow/test_graph_create.py
Labels: bug

#509 explain no longer requires graph ID, execution-plan is returned as a …
  src/commands/cmd_explain.c
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/graph/graphcontext.c
  tests/flow/test_persistency.py
Labels: enhancement

#513 handle empty query
  src/commands/cmd_explain.c
  src/commands/cmd_query.c
Labels: bug

#529 Improve memory management of All Paths algorithm
  src/algorithms/all_paths.c
  src/algorithms/all_paths.h
  src/algorithms/path.c
  src/algorithms/path.h
  src/execution_plan/ops/op_cond_var_len_traverse.c
Labels: enhancement

#525 Variable-length pattern improvements
  src/execution_plan/optimizations/select_entry_point.c
  src/execution_plan/optimizations/traverse_order.c
  src/graph/graph.c
  tests/flow/test_relation_patterns.py
Labels: bug

#534 graph.explain runs on a dedicated thread
  src/commands/cmd_explain.c
Labels: enhancement

#537 wrong row index within expand-into, enabled few TCK tests
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_expand_into.h
  tests/tck/features/MatchAcceptance2.feature
  tests/tck/features/VarLengthAcceptance.feature
Labels: bug, cypher, enhancement

#539 split algebraic expression on highly connected nodes
  src/arithmetic/algebraic_expression.c
  tests/unit/test_algebraic_expression.cpp
Labels: bug, enhancement
