Repository RedisGraph/RedisGraph, pull requests merged in 2019-05, with the labels that each got.

#492 Transposed adjacency matrix
  src/execution_plan/ops/op_delete.c
  src/graph/graph.c
  src/graph/graph.h
  tests/flow/test_graph_deletion.py
  tests/unit/test_graph.cpp
Labels: enhancement

#494 Fix Record memory leak on heapsort
  src/execution_plan/ops/op_sort.c
Labels: bug

#496 Improved build and limitations documentation
  docs/index.md
  docs/known_limitations.md
Labels: Documentation

#497 sync relation mapping matrix
  src/graph/graph.c
Labels: bug

#498 free write lock when freeing the graph
  src/graph/graph.c
Labels: bug

#503 Update documentation and README to reflect new result set structure
  README.md
  docs/commands.md
  docs/index.md
Labels: Documentation

#506 Delete both nodes and edges using GraphBLAS operations
  src/execution_plan/ops/op_delete.c
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graphcontext.c
  src/util/datablock/datablock.c
  src/util/datablock/datablock.h
  tests/flow/test_graph_deletion.py
  tests/unit/test_datablock.cpp
  tests/unit/test_graph.cpp
Labels: enhancement
