Repository RedisGraph/RedisGraph, pull requests merged in 2020-09, with the labels that each got.

#1326 Enable comments in Cypher queries
  src/ast/cypher_whitelist.c
  tests/flow/test_query_validation.py
Labels: cypher

#1342 Pagerank empty matrix
  docs/commands.md
  src/RG.h
  src/procedures/proc_pagerank.c
  tests/flow/test_pagerank.py
Labels: bug

#1345 CASE...WHEN should only accept truthy values
  src/arithmetic/conditional_funcs/conditional_funcs.c
  tests/flow/test_function_calls.py
Labels: bug

#1347 Minor improvements to query structures and Markdown in docs
  docs/commands.md
Labels: Documentation

#1334 mention properties function is not supported
  docs/cypher_support.md
Labels: Documentation

#1359 Document GRAPH.PROFILE entrypoint (#1294)
  docs/commands.md
Labels: Documentation

#1306 Bfs procedure call
  docs/commands.md
  src/Makefile
  src/algorithms/LAGraph_bfs_pushpull.c
  src/algorithms/LAGraph_bfs_pushpull.h
  src/ast/ast_validations.c
  src/execution_plan/ops/op_procedure_call.c
  src/execution_plan/ops/op_procedure_call.h
  src/graph/entities/edge.h
  src/procedures/proc_bfs.c
  src/procedures/proc_bfs.h
  src/procedures/proc_ctx.h
  src/procedures/proc_fulltext_create_index.c
  src/procedures/proc_fulltext_drop_index.c
  src/procedures/proc_fulltext_query.c
  src/procedures/proc_labels.c
  src/procedures/proc_pagerank.c
  src/procedures/proc_property_keys.c
  src/procedures/proc_relations.c
  src/procedures/procedure.c
  src/procedures/procedure.h
  src/procedures/procedures.h
  tests/flow/test_bfs.py
Labels: enhancement
