Repository RedisGraph/RedisGraph, pull requests merged in 2020-08, with the labels that each got.

#1269 migrate id from entity to both node and edge objects
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_merge.c
  src/graph/entities/edge.h
  src/graph/entities/graph_entity.h
  src/graph/entities/node.h
  src/graph/graph.c
  src/serializers/encoder/v7/encode_graph_entities.c
  src/serializers/graph_extensions.c
  src/util/datablock/datablock_iterator.c
  src/util/datablock/datablock_iterator.h
  tests/unit/test_datablock.cpp
  tests/unit/test_graph.cpp
  tests/unit/test_value.cpp
Labels: enhancement

#1275 avoid deep recursions by introducing multiple RSQNodes under a single…
  src/execution_plan/optimizations/utilize_indices.c
Labels: enhancement

#1266 List comprehension
  docs/commands.md
  docs/cypher_support.md
  src/Makefile
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/arithmetic/comprehension_funcs/comprehension_funcs.c
  src/arithmetic/comprehension_funcs/comprehension_funcs.h
  src/arithmetic/func_desc.c
  src/arithmetic/func_desc.h
  src/arithmetic/funcs.c
  src/arithmetic/funcs.h
  src/arithmetic/list_funcs/list_funcs.c
  src/ast/ast_build_ar_exp.c
  src/ast/ast_build_filter_tree.c
  src/ast/ast_build_filter_tree.h
  src/ast/ast_validations.c
  src/ast/cypher_whitelist.c
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_aggregate.c
  tests/flow/test_comprehension_functions.py
  tests/flow/test_concurrent_query.py
  tests/flow/test_function_calls.py
  tests/tck/features/ListComprehension.feature
  tests/tck/features/SetAcceptance.feature
  tests/tck/features/TypeConversionFunctions.feature
Labels: enhancement

#1277 Any all comprehensions
  docs/commands.md
  docs/cypher_support.md
  src/arithmetic/comprehension_funcs/comprehension_funcs.c
  src/ast/ast_build_ar_exp.c
  src/ast/ast_build_filter_tree.c
  src/ast/ast_validations.c
  src/ast/cypher_whitelist.c
  src/filter_tree/filter_tree.c
  tests/flow/test_comprehension_functions.py
Labels: enhancement

#1274 Query timeout
  docs/configuration.md
  src/commands/cmd_dispatcher.c
  src/commands/cmd_query.c
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/module.c
  src/util/cron.c
  src/util/cron.h
  tests/flow/test_timeout.py
  tests/unit/test_cron.cpp
Labels: enhancement

#1283 Remove redundant scan ops before applying index optimization
  src/execution_plan/optimizations/optimizer.c
  tests/flow/test_index_scans.py
Labels: bug

#1287 Fix Profile endpoint crash on some ValueHashJoin queries
  src/execution_plan/ops/op_value_hash_join.c
Labels: bug

#1294 Document GRAPH.PROFILE entrypoint
  docs/commands.md
Labels: Documentation

#1310 Build apply ops in correct ExecutionPlan scope
  src/execution_plan/execution_plan_reduce_to_apply.c
  tests/flow/test_path_filter.py
Labels: bug

#1317 Fix read of freed records in ExpandIntoFree
  src/execution_plan/ops/op_expand_into.c
Labels: bug

#1318 Change struct member order to eliminate Valgrind complaint
  src/arithmetic/algebraic_expression.h
Labels: bug
