Repository RedisGraph/RedisGraph, pull requests merged in 2020-12, with the labels that each got.

#1465 add stars
  README.md
Labels: Documentation

#1464 Add stars to clients (#1462)
  docs/clients.md
Labels: Documentation

#1456 Added new rust client with async support
  docs/clients.md
Labels: Documentation

#1460 validate clauses following a RETURN clause
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_validations.c
  src/execution_plan/execution_plan.c
  tests/flow/test_query_validation.py
  tests/unit/test_aggregate_functions.cpp
  tests/unit/test_arithmetic_expression.cpp
Labels: cypher

#1469 Add C# clients
  docs/clients.md
Labels: Documentation

#1470 Update README.md
  README.md
Labels: Documentation

#1471 dotnet clients
  docs/clients.md
Labels: Documentation

#1446 Optimize cartesian product scoping
  src/arithmetic/arithmetic_expression.c
  src/execution_plan/optimizations/optimize_cartesian_product.c
  src/value.c
  src/value.h
  tests/flow/test_optimizations_plan.py
Labels: bug

#1475 Fix replacement of unindexed prop when set before indexed prop
  src/execution_plan/ops/op_update.c
  tests/flow/test_index_updates.py
Labels: bug

#1473 Decode IDX_ANY as an exact-match index
  src/schema/schema.c
  src/serializers/decoders/prev/v7/decode_graph_schema.c
Labels: bug

#1480 configure resultset size limit
  docs/commands.md
  src/algorithms/LAGraph_bfs_pushpull.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  src/arithmetic/algebraic_expression/utils.c
  src/commands/cmd_config.c
  src/commands/cmd_config.h
  src/commands/commands.h
  src/config.c
  src/config.h
  src/execution_plan/ops/op_results.c
  src/execution_plan/ops/op_results.h
  src/graph/graph.c
  src/graph/graphcontext.c
  src/module.c
  src/module_event_handlers.c
  src/procedures/proc_bfs.c
  src/resultset/resultset.c
  src/resultset/resultset.h
  src/serializers/encoder/v8/encode_graph.c
  tests/flow/test_config.py
  tests/flow/test_results.py
Labels: enhancement

#1468 Refactor aggregate logic
  src/Makefile
  src/arithmetic/agg_ctx.h
  src/arithmetic/agg_funcs.c
  src/arithmetic/agg_funcs.h
  src/arithmetic/aggregate.c
  src/arithmetic/aggregate.h
  src/arithmetic/aggregate_funcs/agg_funcs.c
  src/arithmetic/aggregate_funcs/agg_funcs.h
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/arithmetic/arithmetic_expression_construct.c
  src/arithmetic/boolean_funcs/boolean_funcs.c
  src/arithmetic/comprehension_funcs/comprehension_funcs.c
  src/arithmetic/conditional_funcs/conditional_funcs.c
  src/arithmetic/entity_funcs/entity_funcs.c
  src/arithmetic/func_desc.c
  src/arithmetic/func_desc.h
  src/arithmetic/funcs.c
  src/arithmetic/funcs.h
  src/arithmetic/list_funcs/list_funcs.c
  src/arithmetic/numeric_funcs/numeric_funcs.c
  src/arithmetic/path_funcs/path_funcs.c
  src/arithmetic/placeholder_funcs/placeholder_funcs.c
  src/arithmetic/repository.c
  src/arithmetic/repository.h
  src/arithmetic/string_funcs/string_funcs.c
  src/arithmetic/time_funcs/time_funcs.c
  src/ast/ast.c
  src/ast/ast_build_op_contexts.c
  src/ast/ast_validations.c
  src/errors.h
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/optimizations/reduce_count.c
  src/module.c
  src/resultset/resultset.c
  src/value.c
  src/value.h
  tests/flow/test_bound_variables.py
  tests/flow/test_function_calls.py
  tests/flow/test_results.py
  tests/tck/features/FunctionsAcceptance.feature
  tests/tck/features/steps/Steps.py
  tests/unit/test_aggregate_functions.cpp
  tests/unit/test_arithmetic_expression.cpp
  tests/unit/test_execution_plan_clone.cpp
Labels: bug

#1393 Replace cache per thread with global cache
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_validations.c
  src/commands/cmd_explain.c
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/commands/execution_ctx.c
  src/commands/execution_ctx.h
  src/config.c
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/util/cache/cache.c
  src/util/cache/cache.h
  src/util/cache/cache_array.c
  src/util/cache/cache_array.h
  tests/flow/test_cache.py
  tests/unit/test_cache.cpp
Labels: enhancement

#1490 Add support for startNode and endNode functions
  docs/cypher_support.md
  src/arithmetic/entity_funcs/entity_funcs.c
  src/value.c
  src/value.h
  tests/flow/test_function_calls.py
  tests/tck/features/MergeRelationshipAcceptance.feature
Labels: enhancement

#1494 Disallow updating properties after deleting their entities
  src/execution_plan/ops/op_update.c
  src/graph/entities/graph_entity.c
  src/graph/entities/graph_entity.h
  src/graph/graph.c
  src/graph/graph.h
  src/util/datablock/datablock.c
  src/util/datablock/datablock.h
  tests/flow/test_graph_deletion.py
Labels: bug

#1496 Disallow assigning properties to complex types in MERGE SET
  src/execution_plan/ops/op_merge.c
  tests/flow/test_query_validation.py
Labels: bug

#1498 Consider both filters and labels in selecting a starting point
  src/execution_plan/optimizations/traverse_order.c
  tests/unit/test_traversal_ordering.cpp
Labels: enhancement

#1495 Don't attempt to access non-existent properties
  docs/known_limitations.md
  src/execution_plan/ops/shared/create_functions.c
  src/graph/entities/graph_entity.c
  tests/flow/test_graph_create.py
  tests/flow/test_graph_merge.py
  tests/flow/test_query_validation.py
Labels: bug

#1503 Error on alias references in parameters
  src/arithmetic/arithmetic_expression_construct.c
  tests/flow/test_query_validation.py
Labels: bug

#1504 Fixes for zero-length traversals
  src/arithmetic/algebraic_expression/algebraic_expression.c
  src/arithmetic/algebraic_expression/utils.c
  src/arithmetic/algebraic_expression/utils.h
  src/ast/ast_build_reference_map.c
  tests/unit/test_algebraic_expression.cpp
Labels: bug
