Repository RedisGraph/RedisGraph, pull requests merged in 2020-03, with the labels that each got.

#977 added id seek clone
  src/execution_plan/ops/op_node_by_id_seek.c
Labels: enhancement

#958 added op aggreage clone
  src/execution_plan/ops/op_aggregate.c
Labels: enhancement

#1006 Add install instructions for OpenMP
  README.md
  docs/index.md
Labels: Documentation

#987 added op sort clone
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_sort.c
  src/execution_plan/ops/op_sort.h
Labels: enhancement

#1004 re-enable graph.profile
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/execution_plan/ops/shared/print_functions.c
  src/resultset/formatters/resultset_formatters.c
  src/resultset/formatters/resultset_formatters.h
  src/resultset/resultset.c
  src/resultset/resultset.h
  tests/flow/test_profile.py
Labels: bug, enhancement

#996 Fix leak on projected heap-allocated graph entities
  src/execution_plan/ops/op_project.c
Labels: bug

#897 GRAPH.SLOWLOG
  docs/commands.md
  src/Makefile
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_context.c
  src/commands/cmd_context.h
  src/commands/cmd_dispatcher.c
  src/commands/cmd_explain.c
  src/commands/cmd_query.c
  src/commands/cmd_slowlog.c
  src/commands/cmd_slowlog.h
  src/commands/commands.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/graph/serializers/decoders/decode_graphcontext.c
  src/module.c
  src/query_ctx.c
  src/slow_log/slow_log.c
  src/slow_log/slow_log.h
  src/util/object_pool/object_pool.c
  src/util/object_pool/object_pool.h
  src/util/thpool/thpool.c
  src/util/thpool/thpool.h
  tests/flow/test_slowlog.py
Labels: enhancement

#1001 Use NOP label scan if range iterator construction fails
  deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c
  src/execution_plan/ops/op.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_index_scan.c
  src/execution_plan/ops/op_node_by_id_seek.c
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/shared/print_functions.c
  src/util/range/unsigned_range.c
  src/util/range/unsigned_range.h
  tests/flow/test_node_by_id.py
  tests/flow/test_profile.py
  tests/unit/test_tuples_iter.cpp
Labels: bug

#1002 Automate leak check
  .circleci/config.yml
  Makefile
  src/Makefile
  src/valgrind.supp
  tests/Makefile
  tests/flow/Makefile
  tests/flow/base.py
  tests/flow/test_bidirectional_traversals.py
  tests/flow/test_bound_variables.py
  tests/flow/test_bulk_insertion.py
  tests/flow/test_concurrent_query.py
  tests/flow/test_distinct.py
  tests/flow/test_function_calls.py
  tests/flow/test_graph_create.py
  tests/flow/test_graph_deletion.py
  tests/flow/test_graph_merge.py
  tests/flow/test_imdb.py
  tests/flow/test_index_scans.py
  tests/flow/test_index_updates.py
  tests/flow/test_list.py
  tests/flow/test_mix_labels.py
  tests/flow/test_multi_exec.py
  tests/flow/test_multi_pattern.py
  tests/flow/test_multiple_edges.py
  tests/flow/test_node_by_id.py
  tests/flow/test_optimizations_plan.py
  tests/flow/test_order_by.py
  tests/flow/test_pagerank.py
  tests/flow/test_params.py
  tests/flow/test_path.py
  tests/flow/test_path_filter.py
  tests/flow/test_persistency.py
  tests/flow/test_procedures.py
  tests/flow/test_profile.py
  tests/flow/test_query_validation.py
  tests/flow/test_relation_patterns.py
  tests/flow/test_rename.py
  tests/flow/test_results.py
  tests/flow/test_reversed_patterns.py
  tests/flow/test_self_pointing_node.py
  tests/flow/test_slowlog.py
  tests/flow/test_social.py
  tests/flow/test_stress.py
  tests/flow/test_union.py
  tests/flow/test_value_comparisons.py
  tests/flow/test_variable_length_traversals.py
  tests/flow/test_with_clause.py
  tests/memcheck.sh
  tests/tck/Makefile
  tests/tck/features/MatchAcceptance2.feature
Labels: enhancement

#1023 Validate arity per-command rather than globally
  src/commands/cmd_dispatcher.c
  tests/flow/test_query_validation.py
Labels: bug

#1028 Fix invalid op sequence when introducing index scans
  src/execution_plan/optimizations/utilize_indices.c
  tests/flow/test_index_scans.py
Labels: bug

#1032 push down transpose operations
  src/arithmetic/algebraic_expression/algebraic_expression_construction.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  tests/flow/test_bidirectional_traversals.py
  tests/flow/test_relation_patterns.py
  tests/unit/test_algebraic_expression.cpp
Labels: bug

#1020 allow skip and limit to be parametes.
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_mock.c
  src/ast/ast_shared.h
  src/ast/ast_validations.c
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_expand_into.h
  src/execution_plan/ops/op_limit.c
  src/execution_plan/ops/op_limit.h
  src/execution_plan/ops/op_skip.c
  src/execution_plan/ops/op_skip.h
  src/execution_plan/ops/op_sort.c
  src/execution_plan/ops/op_sort.h
  src/execution_plan/optimizations/reduce_scans.c
  src/execution_plan/optimizations/reduce_traversal.c
  tests/flow/test_params.py
Labels: bug

#1022 added datablock out of order ops
  src/util/datablock/datablock.c
  src/util/datablock/oo_datablock.c
  src/util/datablock/oo_datablock.h
  tests/unit/test_datablock.cpp
Labels: enhancement
