Repository RedisGraph/RedisGraph, pull requests merged in 2020-06, with the labels that each got.

#1111 Perform one-time transpose of traversed matrices
  src/arithmetic/algebraic_expression.h
  src/arithmetic/algebraic_expression/algebraic_expression.c
  src/arithmetic/algebraic_expression/algebraic_expression_eval.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  src/arithmetic/algebraic_expression/utils.c
  src/arithmetic/algebraic_expression/utils.h
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/shared/print_functions.c
  tests/Makefile
  tests/unit/test_algebraic_expression.cpp
Labels: enhancement

#1118 Omp thread configuration
  docs/configuration.md
  src/config.c
  src/config.h
  src/module.c
  src/module_event_handlers.c
  src/serializers/encoder/v7/encode_graph.c
Labels: Documentation, enhancement

#877 Transposed relations
  docs/configuration.md
  src/arithmetic/algebraic_expression/algebraic_expression_debug.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  src/arithmetic/algebraic_expression/utils.c
  src/arithmetic/algebraic_expression/utils.h
  src/config.c
  src/config.h
  src/graph/graph.c
  src/graph/graph.h
  tests/flow/test_transpose_configurations.py
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_all_paths.cpp
  tests/unit/test_graph.cpp
Labels: enhancement

#1148 Avoid flushing matrices by maintaining separate transpose edge arrays
  src/graph/graph.c
Labels: enhancement

#1165 Resolve race in accessing/updating attribute maps
  src/arithmetic/arithmetic_expression.c
  src/ast/ast_build_op_contexts.c
  src/ast/ast_build_op_contexts.h
  src/ast/ast_shared.c
  src/ast/ast_shared.h
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_update.h
  src/graph/graph.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_execution_plan_clone.cpp
  tests/unit/test_filter_tree.cpp
  tests/unit/test_index.cpp
Labels: bug

#1169 Move index iterator construction to first Consume call
  src/execution_plan/ops/op_index_scan.c
  src/execution_plan/ops/op_index_scan.h
  src/execution_plan/optimizations/utilize_indices.c
  tests/flow/test_index_scans.py
Labels: bug
