Repository RedisGraph/RedisGraph, pull requests merged in 2020-07, with the labels that each got.

#1226 relay on search replace add functionality to delete existing documents
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/shared/create_functions.c
  src/schema/schema.c
  src/schema/schema.h
Labels: bug

#1212 Emit compile time error on creation of undirected edges
  src/ast/ast_validations.c
  tests/flow/test_query_validation.py
  tests/tck/features/CreateAcceptance.feature
  tests/tck/features/MiscellaneousErrorAcceptance.feature
  tests/tck/features/steps/Steps.py
Labels: bug, cypher

#1225 Update index on change
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_update.h
  src/graph/entities/node.h
  src/index/index.h
  src/schema/schema.c
Labels: enhancement

#1262 Ignore NULL values in ValueHashJoin
  src/execution_plan/ops/op_value_hash_join.c
  tests/flow/test_null_handling.py
Labels: bug

#1250 Improve label logic
  src/algorithms/all_paths.c
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_index_scan.c
  src/execution_plan/ops/op_merge_create.c
  src/execution_plan/ops/op_node_by_id_seek.c
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/shared/create_functions.c
  src/graph/entities/node.c
  src/graph/entities/node.h
  src/graph/entities/qg_node.c
  src/graph/entities/qg_node.h
  src/graph/graph.c
  src/graph/query_graph.c
  src/index/index.c
  src/procedures/proc_fulltext_query.c
  src/procedures/proc_pagerank.c
  src/resultset/formatters/resultset_replycompact.c
  src/resultset/formatters/resultset_replyverbose.c
  tests/unit/test_bfs.cpp
  tests/unit/test_detect_cycle.cpp
  tests/unit/test_dfs.cpp
  tests/unit/test_query_graph.cpp
  tests/unit/test_traversal_ordering.cpp
Labels: enhancement
