Repository RedisGraph/RedisGraph, pull requests merged in 2020-10, with the labels that each got.

#1365 Support array properties in bulk loader
  src/bulk_insert/bulk_insert.c
Labels: enhancement

#1363 Add no_multi_key & hash_policy
  ramp.yml
Labels: enhancement

#1371 Add GRAPH.BULK documentation and link to bulk loader documentation
  docs/bulk_spec.md
  docs/index.md
  mkdocs.yml
Labels: Documentation

#1372 Allow upper case letters in proc names
  src/arithmetic/func_desc.c
  src/arithmetic/repository.c
  src/arithmetic/string_funcs/string_funcs.c
  src/procedures/procedure.c
  src/procedures/procedure.h
  src/util/strutil.c
  src/util/strutil.h
  tests/flow/test_procedures.py
Labels: bug

#1377 Adding a new procedure that returns all the procedures in the system
  src/ast/ast.c
  src/execution_plan/ops/op_procedure_call.c
  src/procedures/proc_ctx.h
  src/procedures/proc_procedures.c
  src/procedures/proc_procedures.h
  src/procedures/procedure.c
  src/procedures/procedure.h
  src/procedures/procedures.h
  tests/flow/test_procedures.py
Labels: new feature

#1380 Replace rightmost operand if traversing from dest->src (#1295)
  src/arithmetic/algebraic_expression.h
  src/arithmetic/algebraic_expression/algebraic_expression.c
  src/arithmetic/algebraic_expression/algebraic_expression_construction.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  src/arithmetic/algebraic_expression/utils.c
  src/arithmetic/algebraic_expression/utils.h
  src/execution_plan/execution_plan.c
  tests/flow/test_algebraic_expression_order.py
Labels: bug

#1381 Always set GraphCtx in QueryCtx while decoding graph keys
  src/serializers/decoders/current/v7/decode_graph.c
  tests/flow/test_v7_encode_decode.py
Labels: bug

#1386 Avoid double free of heap-allocated values in CASE...WHEN statements
  src/arithmetic/conditional_funcs/conditional_funcs.c
  tests/flow/test_function_calls.py
Labels: bug

#1389 Allow property accesses on non-identifier entity references
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/arithmetic/arithmetic_expression_construct.c
  src/arithmetic/entity_funcs/entity_funcs.c
  src/ast/ast_build_filter_tree.c
  src/ast/ast_build_reference_map.c
  src/execution_plan/execution_plan_build/build_call_op.c
  src/execution_plan/execution_plan_build/build_projection_ops.c
  src/execution_plan/optimizations/apply_join.c
  src/execution_plan/optimizations/reduce_count.c
  src/execution_plan/optimizations/utilize_indices.c
  tests/flow/test_optimizations_plan.py
  tests/flow/test_path.py
  tests/flow/test_query_validation.py
  tests/tck/features/steps/Steps.py
  tests/unit/test_filter_tree.cpp
  tests/unit/test_traversal_ordering.cpp
Labels: bug

#1397 redundent filter construction and placement
  src/arithmetic/placeholder_funcs/placeholder_funcs.c
  src/execution_plan/execution_plan_build/build_match_op_tree.c
  src/execution_plan/execution_plan_build/reduce_to_apply.c
  tests/flow/test_optional_match.py
Labels: bug

#1298 Parse full argv array on main thread
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_context.c
  src/commands/cmd_context.h
  src/commands/cmd_dispatcher.c
  src/commands/cmd_query.c
Labels: bug

#1406 query validation should not check if procedure outputs been defined
  src/ast/ast_validations.c
  tests/flow/test_query_validation.py
Labels: bug
