Repository RedisGraph/RedisGraph, pull requests merged in 2020-01, with the labels that each got.

#846 Fix invalid read on freed filter op
  src/execution_plan/optimizations/seek_by_id.c
Labels: bug

#855 unwind should let record determine element type
  src/execution_plan/ops/op_unwind.c
  tests/tck/features/UnwindAcceptance.feature
Labels: bug

#849 Bidirectional traversals
  docs/commands.md
  docs/cypher_support.md
  src/algorithms/all_paths.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_conditional_traverse.h
  tests/flow/test_bidirectional_traversals.py
  tests/flow/test_variable_length_traversals.py
  tests/tck/features/AggregationAcceptance.feature
  tests/tck/features/CreateAcceptance.feature
  tests/tck/features/MatchAcceptance.feature
  tests/tck/features/MatchAcceptance2.feature
  tests/tck/features/MatchingSelfRelationships.feature
  tests/tck/features/MergeRelationshipAcceptance.feature
  tests/tck/features/WithAcceptance.feature
Labels: enhancement

#862 make sure removed operand is diagonal
  src/execution_plan/execution_plan.c
  src/execution_plan/optimizations/traverse_order.c
Labels: bug

#865 Only remove Distinct ops with an Aggregate child
  src/execution_plan/optimizations/reduce_distinct.c
  tests/flow/test_optimizations_plan.py
Labels: bug

#868 Transpose the deletion mask before updating the transposed adjacency matrix
  src/graph/graph.c
  tests/flow/test_graph_deletion.py
Labels: bug

#872 ObjectPool for Records and generic allocations
  src/Makefile
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  src/execution_plan/ops/op.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_aggregate.c
  src/execution_plan/ops/op_all_node_scan.c
  src/execution_plan/ops/op_apply.c
  src/execution_plan/ops/op_apply_multiplexer.c
  src/execution_plan/ops/op_argument.c
  src/execution_plan/ops/op_cartesian_product.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_distinct.c
  src/execution_plan/ops/op_expand_into.c
  src/execution_plan/ops/op_filter.c
  src/execution_plan/ops/op_index_scan.c
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_merge_create.c
  src/execution_plan/ops/op_node_by_id_seek.c
  src/execution_plan/ops/op_node_by_label_scan.c
  src/execution_plan/ops/op_procedure_call.c
  src/execution_plan/ops/op_project.c
  src/execution_plan/ops/op_semi_apply.c
  src/execution_plan/ops/op_skip.c
  src/execution_plan/ops/op_sort.c
  src/execution_plan/ops/op_unwind.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_value_hash_join.c
  src/execution_plan/record.c
  src/execution_plan/record.h
  src/graph/graphcontext.c
  src/grouping/group.c
  src/util/block.c
  src/util/block.h
  src/util/datablock/block.h
  src/util/datablock/datablock.c
  src/util/datablock/datablock.h
  src/util/datablock/datablock_iterator.c
  src/util/datablock/datablock_iterator.h
  src/util/object_pool/object_pool.c
  src/util/object_pool/object_pool.h
  tests/unit/test_datablock.cpp
  tests/unit/test_object_pool.cpp
Labels: enhancement

#876 add types include
  src/util/block.h
Labels: bug

#883 Update documentation to reflect recent changes
  docs/commands.md
  docs/cypher_support.md
  docs/index.md
  docs/known_limitations.md
Labels: Documentation

#893 Preserve the children array order when replacing ops
  src/execution_plan/execution_plan_modify.c
  tests/flow/test_optimizations_plan.py
Labels: bug

#895 Support float inputs for modulo computations
  src/arithmetic/numeric_funcs/numeric_funcs.c
  src/value.c
  tests/flow/test_function_calls.py
Labels: enhancement
