Repository RedisGraph/RedisGraph, pull requests merged in 2020-11, with the labels that each got.

#1408 Fuzzy test crashes
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression_construct.c
  src/arithmetic/boolean_funcs/boolean_funcs.c
  src/ast/ast_validations.c
  src/ast/cypher_whitelist.c
  src/errors.c
  src/errors.h
  src/execution_plan/execution_plan_build/execution_plan_construct.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_unwind.c
  src/execution_plan/optimizations/compact_filters.c
  src/execution_plan/optimizations/optimize_cartesian_product.c
  tests/flow/test_optimizations_plan.py
  tests/flow/test_optional_match.py
  tests/flow/test_query_validation.py
  tests/flow/test_variable_length_traversals.py
Labels: bug

#1382 Graph version
  src/commands/cmd_dispatcher.c
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/query_ctx.c
  src/resultset/resultset.c
  src/resultset/resultset_statistics.c
  src/resultset/resultset_statistics.h
  src/util/uuid.h
  tests/flow/test_cache.py
  tests/flow/test_graph_versioning.py
Labels: bug

#1429 Fuzzy test crashes 2
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/ast/ast_build_filter_tree.c
  src/ast/ast_validations.c
  src/execution_plan/optimizations/compact_filters.c
  src/filter_tree/filter_tree.c
  tests/flow/test_query_validation.py
  tests/unit/test_filter_tree.cpp
Labels: bug

#1432 Disallow property assignment to complex data types
  src/errors.c
  src/errors.h
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/shared/create_functions.c
  src/graph/entities/graph_entity.c
  src/value.h
  tests/flow/test_query_validation.py
Labels: bug

#1437 Don't assert on failed MERGE updates
  src/execution_plan/ops/op_merge.c
  tests/flow/test_graph_merge.py
Labels: bug

#1431 Disallow traversal patterns outside of the appropriate clauses
  src/ast/ast_validations.c
  tests/flow/test_query_validation.py
Labels: bug

#1333 add redis-cli parameter example
  docs/cypher_support.md
Labels: Documentation

#1440 Fix warnings reported by fb-infer
  src/arithmetic/algebraic_expression/algebraic_expression_construction.c
  src/arithmetic/algebraic_expression/algebraic_expression_eval.c
  src/arithmetic/entity_funcs/entity_funcs.c
  src/ast/ast.c
  src/ast/ast_build_op_contexts.c
  src/ast/ast_validations.c
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan_build/build_projection_ops.c
  src/execution_plan/ops/op_apply_multiplexer.c
  src/execution_plan/ops/op_filter.c
  src/execution_plan/ops/op_semi_apply.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/shared/create_functions.c
  src/execution_plan/optimizations/utilize_indices.c
  src/graph/entities/qg_node.c
  src/index/index.c
  src/serializers/decoders/prev/v4/decode_graph.c
  src/serializers/encoder/v8/encode_graph_entities.c
Labels: fbinfer

#1450 Document dbms.procedures()
  docs/commands.md
Labels: Documentation

#1442 Disallow MERGE of entities with null properties
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression_construct.c
  src/arithmetic/comprehension_funcs/comprehension_funcs.c
  src/arithmetic/list_funcs/list_funcs.c
  src/ast/ast_build_filter_tree.c
  src/ast/ast_validations.c
  src/commands/cmd_delete.c
  src/commands/cmd_explain.c
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/errors.c
  src/errors.h
  src/execution_plan/execution_plan.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_limit.c
  src/execution_plan/ops/op_merge_create.c
  src/execution_plan/ops/op_skip.c
  src/execution_plan/ops/op_unwind.c
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/shared/create_functions.c
  src/execution_plan/ops/shared/create_functions.h
  src/filter_tree/filter_tree.c
  src/graph/entities/graph_entity.c
  src/module.c
  src/procedures/proc_fulltext_query.c
  src/query_ctx.c
  src/query_ctx.h
  src/resultset/resultset.c
  src/valgrind.supp
  src/value.h
  tests/flow/test_graph_create.py
  tests/flow/test_graph_merge.py
  tests/flow/test_persistency.py
  tests/tck/features/CreateAcceptance.feature
Labels: bug
