Repository RedisGraph/RedisGraph, pull requests merged in 2021-01, with the labels that each got.

#1519 list indices
  docs/commands.md
  src/graph/graphcontext.c
  src/procedures/proc_list_indexes.c
  src/procedures/proc_list_indexes.h
  src/procedures/procedure.c
  src/procedures/procedures.h
  src/schema/schema.c
  tests/flow/test_procedures.py
Labels: cypher

#1523 Recurse into other operations when checking for transpose ops
  src/arithmetic/algebraic_expression.h
  src/arithmetic/algebraic_expression/algebraic_expression.c
  src/arithmetic/algebraic_expression/algebraic_expression_construction.c
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  src/execution_plan/ops/shared/print_functions.c
  src/execution_plan/ops/shared/traverse_functions.c
  tests/flow/test_relation_patterns.py
  tests/unit/test_algebraic_expression.cpp
Labels: bug

#1524 Persist Record values before storing them in OpCreate
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_create.c
  tests/flow/test_graph_create.py
Labels: bug

#1534 Ensure label data is up-to-date when initializing index scans
  src/execution_plan/ops/op_index_scan.c
  tests/flow/test_cache.py
Labels: bug

#1532 Don't attempt to normalize IN filters when utilizing indexes
  src/execution_plan/optimizations/utilize_indices.c
  tests/flow/test_index_scans.py
Labels: bug

#1541 Fix orphaned record in OpApply
  src/execution_plan/ops/op_apply.c
Labels: bug

#1548 Update on change
  src/execution_plan/ops/op_update.c
  src/graph/entities/graph_entity.c
  src/graph/entities/graph_entity.h
  tests/flow/test_entity_update.py
  tests/flow/test_graph_merge.py
  tests/flow/test_index_updates.py
Labels: enhancement

#1555 Add support for raw identifiers in map projections
  src/arithmetic/arithmetic_expression_construct.c
  tests/flow/test_map.py
Labels: bug
