Repository RedisGraph/RedisGraph, pull requests merged in 2021-03, with the labels that each got.

#1596 Threaded bulk insert
  .astylerc
  demo/bulk_insert/README.md
  demo/bulk_insert/bulk_insert.py
  demo/bulk_insert/requirements.txt
  demo/social/resources/bulk_formatted/Country.csv
  demo/social/resources/bulk_formatted/KNOWS.csv
  demo/social/resources/bulk_formatted/Person.csv
  demo/social/resources/bulk_formatted/VISITED.csv
  src/bulk_insert/bulk_insert.c
  src/bulk_insert/bulk_insert.h
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_dispatcher.c
  src/module.c
  src/util/thpool/pools.c
  src/util/thpool/pools.h
  tests/flow/test_bulk_insertion.py
  tests/requirements.txt
  tests/unit/test_thread_pools.cpp
Labels: enhancement

#1618 wrongly assumed add op had only 2 operands
  src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
  tests/flow/test_bidirectional_traversals.py
  tests/flow/test_bulk_insertion.py
  tests/flow/test_relation_patterns.py
  tests/unit/test_algebraic_expression.cpp
Labels: bug

#1610 Runtime timeouts
  docs/configuration.md
  src/commands/cmd_dispatcher.c
  src/commands/cmd_query.c
  src/config.c
  src/config.h
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan.h
  tests/flow/test_timeout.py
Labels: enhancement

#1627 Shortest path func
  docs/commands.md
  src/algorithms/LAGraph_bfs_pushpull.c
  src/algorithms/LAGraph_bfs_pushpull.h
  src/arithmetic/arithmetic_expression_construct.c
  src/arithmetic/path_funcs/path_funcs.c
  src/arithmetic/path_funcs/path_funcs.h
  src/ast/ast_build_reference_map.c
  src/ast/ast_validations.c
  src/ast/cypher_whitelist.c
  src/graph/graph.c
  src/graph/query_graph.c
  src/procedures/proc_bfs.c
  tests/flow/test_shortest_path.py
Labels: cypher, new feature

#1632 Emit a single error on failed GraphContext retrieval
  src/commands/cmd_bulk_insert.c
  tests/flow/test_bulk_insertion.py
Labels: bug

#1637 Julia client
  docs/clients.md
Labels: Documentation

#1644 Fix label retrieval on cached unknown value
  src/graph/entities/node.h
Labels: bug
