Repository RedisGraph/RedisGraph, pull requests merged in 2021-09, with the labels that each got.

#1905 Update endpoint documentation with reference to timeout arg
  docs/commands.md
Labels: Documentation

#1904 Allow reconfiguring several configuration fields to 0 (default)
  src/configuration/config.c
  tests/flow/test_config.py
Labels: bug

#1915 validate functions ref within params [WIP]
  src/ast/ast_validations.c
  tests/flow/test_params.py
Labels: bug

#1913 Update thread-local AST for every cloned op
  src/algorithms/all_paths.c
  src/execution_plan/execution_plan_clone.c
  tests/flow/test_variable_length_traversals.py
Labels: bug

#1897 Aliases in WITH...ORDER BY must be valid references
  src/ast/ast_validations.c
  tests/flow/test_with_clause.py
Labels: bug

#1931 sync matrices on parent process before fork
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan_build/build_match_op_tree.c
  src/graph/entities/qg_node.c
  src/graph/query_graph.c
  src/module_event_handlers.c
  tests/flow/test_persistency.py
  tests/flow/test_stress.py
Labels: bug

#1898 Error when setting a property to an array containing an invalid type
  src/datatypes/array.c
  src/datatypes/array.h
  src/execution_plan/ops/shared/create_functions.c
  src/execution_plan/ops/shared/update_functions.c
  tests/flow/test_entity_update.py
  tests/flow/test_graph_create.py
  tests/unit/test_value.cpp
Labels: bug

#1944 Update links in docs to point to redis.com
  docs/References.md
  docs/clients.md
  docs/commands.md
  docs/index.md
Labels: Documentation

#1942 transposed delta matrix should be cols X rows
  src/graph/rg_matrix/rg_new.c
  src/graph/rg_matrix/rg_resize.c
  tests/unit/test_rg_matrix.cpp
Labels: bug

#1933 Free thread-local data on graph deletion
  src/arithmetic/arithmetic_expression.c
  src/ast/ast.c
  src/commands/cmd_bulk_insert.c
  src/graph/graphcontext.c
  src/query_ctx.c
  src/query_ctx.h
Labels: bug

#1945 Track node count per label in graph statistics
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graph_statistics.c
  src/graph/graph_statistics.h
  src/serializers/decoders/current/v9/decode_graph.c
  src/serializers/decoders/prev/v6/decode_graph.c
  src/serializers/decoders/prev/v7/decode_graph.c
  src/serializers/decoders/prev/v8/decode_graph.c
  tests/unit/test_graph.cpp
Labels: enhancement
