Repository RedisGraph/RedisGraph, pull requests merged in 2021-06, with the labels that each got.

#1388 Node creation buffer
  src/configuration/config.c
  src/configuration/config.h
  src/execution_plan/ops/op_node_by_id_seek.c
  src/graph/graph.c
  src/graph/graph.h
  src/procedures/proc_pagerank.c
  src/serializers/decoders/current/v9/decode_graph.c
  src/serializers/decoders/current/v9/decode_graph_entities.c
  src/util/datablock/datablock.c
  src/util/datablock/datablock.h
  src/util/datablock/oo_datablock.c
  tests/flow/test_v7_encode_decode.py
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_graph.cpp
Labels: enhancement

#1741 Improve edge extraction
  src/algorithms/algorithms.h
  src/algorithms/all_neighbors.c
  src/algorithms/all_neighbors.h
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_cond_var_len_traverse.h
  src/execution_plan/optimizations/traverse_order_utils.c
  src/graph/entities/qg_edge.c
  src/graph/entities/qg_edge.h
  src/graph/graph.c
  src/graph/graph.h
Labels: enhancement

#1749 Support updating properties with map referenced by parameter or variable
  src/ast/ast_build_op_contexts.c
  src/ast/ast_shared.h
  src/commands/cmd_explain.c
  src/commands/cmd_profile.c
  src/commands/cmd_query.c
  src/commands/execution_ctx.c
  src/commands/execution_ctx.h
  src/datatypes/map.c
  src/datatypes/map.h
  src/execution_plan/ops/shared/update_functions.c
  tests/flow/test_entity_update.py
Labels: bug

#1754 map should return volatile data
  src/datatypes/map.c
Labels: bug

#1773 matrix resize doesn't set both rows and columns atomically
  src/graph/graph.c
Labels: bug

#1768 Add fuzz testing local step and CI integration
  .circleci/config.yml
  Makefile
  src/Makefile
  tests/Makefile
  tests/fuzz/Makefile
  tests/fuzz/generator/CustomCypherGenerator.py
  tests/fuzz/generator/CypherGenerator.py
  tests/fuzz/process.py
  tests/requirements.txt
Labels: enhancement

#1783 use individual edge deletion when number of edges to delete is small
  src/execution_plan/ops/op_delete.c
  src/graph/graph.c
  src/query_ctx.c
  tests/benchmarks/explicit_edge_deletion.yml
Labels: enhancement

#1792 Add documentation for startNode() and endNode()
  docs/commands.md
Labels: Documentation

#1791 Fix memory leak on AllNeighborsCtx_Reset
  src/algorithms/all_neighbors.c
Labels: bug

#1793 Don't use bulk routine for implicit edge deletion <= 4
  src/execution_plan/ops/op_delete.c
  src/graph/graph.c
  src/graph/graph.h
  tests/benchmarks/implicit_edge_deletion.yml
Labels: enhancement
