Repository RedisGraph/RedisGraph, pull requests merged in 2021-04, with the labels that each got.

#1649 GRAPH.LIST lists all graph keys in keyspace (no support for cluster env)
  docs/commands.md
  src/commands/cmd_bulk_insert.c
  src/commands/cmd_bulk_insert.h
  src/commands/cmd_config.c
  src/commands/cmd_config.h
  src/commands/cmd_delete.c
  src/commands/cmd_delete.h
  src/commands/cmd_dispatcher.h
  src/commands/cmd_explain.c
  src/commands/cmd_explain.h
  src/commands/cmd_list.c
  src/commands/cmd_profile.c
  src/commands/cmd_profile.h
  src/commands/cmd_query.c
  src/commands/cmd_query.h
  src/commands/cmd_slowlog.c
  src/commands/cmd_slowlog.h
  src/commands/commands.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/module.c
  tests/flow/test_list.py
Labels: enhancement

#1653 add sqrt function
  docs/commands.md
  src/arithmetic/numeric_funcs/numeric_funcs.c
  tests/tck/features/expressions/mathematical/Mathematical13.feature
  tests/unit/test_arithmetic_expression.cpp
Labels: cypher

#1650 Fix memory leak on allocated keys in OpAggregate
  src/arithmetic/arithmetic_expression_construct.c
  src/execution_plan/ops/op_aggregate.c
  src/serializers/decoders/current/v9/decode_graph_entities.c
  tests/flow/test_function_calls.py
  tests/flow/test_map.py
Labels: bug

#1656 drain thread pools before shutting down
  src/module_event_handlers.c
  src/util/thpool/pools.c
  src/util/thpool/pools.h
  src/util/thpool/thpool.c
  tests/flow/test_stress.py
  tests/unit/test_thread_pools.cpp
Labels: bug

#1657 Support filtering on variable-length edges in traversals
  src/algorithms/all_paths.c
  src/algorithms/all_paths.h
  src/ast/ast_validations.c
  src/execution_plan/execution_plan_build/build_match_op_tree.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_cond_var_len_traverse.h
  src/execution_plan/ops/op_filter.c
  src/execution_plan/optimizations/apply_join.c
  src/execution_plan/optimizations/apply_join.h
  src/execution_plan/optimizations/apply_limit.c
  src/execution_plan/optimizations/apply_limit.h
  src/execution_plan/optimizations/apply_skip.c
  src/execution_plan/optimizations/apply_skip.h
  src/execution_plan/optimizations/compact_filters.c
  src/execution_plan/optimizations/compact_filters.h
  src/execution_plan/optimizations/filter_variable_length_edges.c
  src/execution_plan/optimizations/optimizations.h
  src/execution_plan/optimizations/optimize_cartesian_product.c
  src/execution_plan/optimizations/optimize_cartesian_product.h
  src/execution_plan/optimizations/optimizer.c
  src/execution_plan/optimizations/reduce_count.c
  src/execution_plan/optimizations/reduce_count.h
  src/execution_plan/optimizations/reduce_distinct.c
  src/execution_plan/optimizations/reduce_distinct.h
  src/execution_plan/optimizations/reduce_filters.c
  src/execution_plan/optimizations/reduce_filters.h
  src/execution_plan/optimizations/reduce_scans.c
  src/execution_plan/optimizations/reduce_scans.h
  src/execution_plan/optimizations/reduce_traversal.c
  src/execution_plan/optimizations/reduce_traversal.h
  src/execution_plan/optimizations/seek_by_id.c
  src/execution_plan/optimizations/seek_by_id.h
  src/execution_plan/optimizations/traverse_order.c
  src/execution_plan/optimizations/traverse_order.h
  src/execution_plan/optimizations/utilize_indices.c
  src/execution_plan/optimizations/utilize_indices.h
  src/execution_plan/record.c
  src/execution_plan/record.h
  tests/flow/test_variable_length_traversals.py
  tests/unit/test_all_paths.cpp
  tests/unit/test_traversal_ordering.cpp
Labels: enhancement

#1664 Limit threadpool queue size
  docs/configuration.md
  src/commands/cmd_context.c
  src/commands/cmd_dispatcher.c
  src/commands/execution_ctx.c
  src/config.c
  src/config.h
  src/errors.h
  src/util/thpool/pools.c
  src/util/thpool/pools.h
  src/util/thpool/thpool.c
  src/util/thpool/thpool.h
  tests/flow/test_pending_queries_limit.py
  tests/unit/test_thread_pools.cpp
Labels: enhancement

#1668 Apply path filters after all other filters
  src/execution_plan/execution_plan_build/execution_plan_construct.c
  tests/flow/test_path_filter.py
Labels: enhancement

#1641 Runtime index utilisation
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/arithmetic_expression.h
  src/arithmetic/entity_funcs/entity_funcs.c
  src/execution_plan/execution_plan_build/execution_plan_construct.c
  src/execution_plan/ops/op_index_scan.c
  src/execution_plan/ops/op_index_scan.h
  src/execution_plan/optimizations/utilize_indices.c
  src/execution_plan/record.c
  src/execution_plan/record.h
  src/filter_tree/filter_tree.c
  src/filter_tree/filter_tree.h
  src/filter_tree/filter_tree_utils.c
  src/filter_tree/filter_tree_utils.h
  src/filter_tree/ft_to_rsq.c
  src/filter_tree/ft_to_rsq.h
  src/index/index.c
  src/index/index.h
  src/value.h
  tests/flow/test_index_scans.py
Labels: enhancement

#1671 disallow aggregations in maps
  docs/datatypes.md
  src/ast/ast_validations.c
  src/execution_plan/execution_plan_build/build_projection_ops.c
  tests/tck/features/clauses/return/Return4.feature
  tests/tck/features/clauses/return/Return6.feature
Labels: bug, cypher

#1675 Fix possible string buffer overflow in array toString logic
  src/datatypes/array.c
Labels: bug
