Repository RedisGraph/RedisGraph, pull requests merged in 2021-07, with the labels that each got.

#1789 Add codecov badge
  README.md
Labels: Documentation

#1832 support value extraction from tuple iterator
  deps/GraphBLAS/Config/GraphBLAS.h.in
  deps/GraphBLAS/Include/GraphBLAS.h
  deps/GraphBLAS/README.md
  deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c
  src/algorithms/all_neighbors.c
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/op_conditional_traverse.c
  src/execution_plan/ops/op_node_by_label_scan.c
  src/graph/graph.c
  src/graph/graph.h
  src/index/index.c
  src/procedures/proc_bfs.c
  src/serializers/encoder/v9/encode_graph_entities.c
  tests/unit/test_graph.cpp
  tests/unit/test_tuples_iter.cpp
Labels: enhancement

#1841 handle empty matrix
  deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c
Labels: bug

#1848 Check all indexes when updating indexed property
  src/schema/schema.c
  tests/flow/test_index_updates.py
Labels: bug
