Repository RedisGraph/RedisGraph, pull requests merged in 2021-08, with the labels that each got.

#1851 OpDistinct does not unique ORDER BY expressions
  src/execution_plan/execution_plan.c
  src/execution_plan/execution_plan_build/build_projection_ops.c
  src/execution_plan/ops/op_distinct.c
  src/execution_plan/ops/op_distinct.h
  tests/flow/test_distinct.py
  tests/flow/test_union.py
Labels: bug

#1862 [fix] Adjusted VARIABLE_LENGTH_EXPAND_INTO KPIs
  tests/benchmarks/variable_length_traversal.yml
Labels: skip-changelog

#1871 optimize matrix sync policy
  src/bulk_insert/bulk_insert.c
  src/commands/cmd_query.c
  src/execution_plan/ops/shared/create_functions.c
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graphcontext.c
  src/module_event_handlers.c
  src/serializers/decoders/current/v9/decode_graph.c
  src/serializers/decoders/current/v9/decode_graph_entities.c
  src/serializers/decoders/prev/v5/decode_graph.c
  src/serializers/decoders/prev/v6/decode_graph.c
  src/serializers/decoders/prev/v7/decode_graph.c
  src/serializers/decoders/prev/v8/decode_graph.c
  src/serializers/decoders/prev/v8/decode_graph_entities.c
  src/serializers/graph_extensions.c
  src/serializers/graph_extensions.h
Labels: enhancement

#1872 m always sparse, dp and dm always hyper
  deps/GraphBLAS/Source/GxB_Pending.c
  src/graph/graph.c
  src/graph/graph.h
  src/graph/rg_matrix/rg_matrix.h
  src/graph/rg_matrix/rg_new.c
  src/graph/rg_matrix/rg_nvals.c
  src/graph/rg_matrix/rg_pending.c
  src/graph/rg_matrix/rg_set_element_uint64.c
  src/graph/rg_matrix/rg_utils.c
  src/module_event_handlers.c
  src/serializers/decoders/current/v9/decode_graph.c
  src/serializers/decoders/prev/v5/decode_graph.c
  src/serializers/decoders/prev/v6/decode_graph.c
  src/serializers/decoders/prev/v7/decode_graph.c
  src/serializers/decoders/prev/v8/decode_graph.c
  src/serializers/graph_extensions.h
  tests/unit/test_algebraic_expression.cpp
  tests/unit/test_rg_matrix.cpp
Labels: bug

#1884 fix #1879 fix readme example
  README.md
Labels: Documentation

#1889 Tuple iterator now updates properly when changing matrix to serialize
  src/serializers/encoder/v9/encode_graph_entities.c
  tests/flow/test_encode_decode.py
Labels: bug
