Repository RedisGraph/RedisGraph, pull requests merged in 2021-05, with the labels that each got.

#1639 Set all properties
  docs/commands.md
  src/algorithms/algorithms.h
  src/algorithms/bfs.h
  src/algorithms/dfs.h
  src/ast/ast_build_op_contexts.c
  src/ast/ast_build_op_contexts.h
  src/ast/ast_build_reference_map.c
  src/ast/ast_shared.c
  src/ast/ast_shared.h
  src/ast/cypher_whitelist.c
  src/datatypes/path/path.h
  src/execution_plan/execution_plan_build/build_merge_op_tree.c
  src/execution_plan/execution_plan_build/build_projection_ops.c
  src/execution_plan/execution_plan_build/execution_plan_construct.c
  src/execution_plan/ops/op_aggregate.h
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_merge.h
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_update.h
  src/execution_plan/ops/shared/update_functions.c
  src/execution_plan/ops/shared/update_functions.h
  src/graph/entities/edge.h
  src/graph/entities/graph_entity.c
  src/graph/entities/graph_entity.h
  src/graph/entities/qg_node.h
  src/graph/graph.h
  src/graph/graphcontext.c
  src/graph/graphcontext.h
  src/index/index.c
  src/util/rax_extensions.c
  src/util/rax_extensions.h
  tests/flow/test_entity_update.py
  tests/flow/test_graph_merge.py
  tests/flow/test_index_updates.py
  tests/flow/test_query_validation.py
  tests/tck/features/clauses/set/Set1.feature
  tests/tck/features/clauses/set/Set4.feature
  tests/tck/features/clauses/set/Set5.feature
  tests/tck/utils/assertions.py
Labels: cypher, enhancement

#1678 multiple use for rax in proc call validation
  src/ast/ast_validations.c
  tests/flow/test_query_validation.py
Labels: bug

#1325 Refactor selection of optimal order for AlgebraicExpressions
  src/arithmetic/algebraic_expression/algebraic_expression_debug.c
  src/execution_plan/optimizations/traverse_order.c
  src/execution_plan/optimizations/traverse_order_utils.c
  src/execution_plan/optimizations/traverse_order_utils.h
  src/filter_tree/filter_tree.c
  src/filter_tree/filter_tree.h
  src/graph/entities/qg_edge.c
  src/graph/entities/qg_edge.h
  src/graph/entities/qg_node.c
  src/graph/entities/qg_node.h
  src/graph/query_graph.c
  tests/flow/test_algebraic_expression_order.py
  tests/flow/test_traversal_construction.py
  tests/unit/test_arithmetic_expression.cpp
  tests/unit/test_bfs.cpp
  tests/unit/test_detect_cycle.cpp
  tests/unit/test_dfs.cpp
  tests/unit/test_filter_tree.cpp
  tests/unit/test_query_graph.cpp
  tests/unit/test_traversal_ordering.cpp
Labels: bug, enhancement

#1703 compute distinct hash only on projected values
  src/execution_plan/ops/op.c
  src/execution_plan/ops/op.h
  src/execution_plan/ops/op_distinct.c
  src/execution_plan/ops/op_distinct.h
  src/execution_plan/record.c
  src/execution_plan/record.h
  tests/flow/test_distinct.py
Labels: bug

#1708 Fix regression in GRAPH.CONFIG GET *
  src/configuration/config.c
  tests/flow/test_config.py
Labels: bug

#1714 ignore bound node when constructing a scan op for it
  src/execution_plan/execution_plan_build/build_match_op_tree.c
  src/execution_plan/execution_plan_build/build_merge_op_tree.c
  tests/flow/test_bound_variables.py
Labels: bug

#1716 flush matrix only if dirty
  src/graph/graph.c
  src/graph/graph.h
Labels: enhancement

#1712 Should take lock before fork only on BGSAVE flow and not RedisSearch GC.
  src/module_event_handlers.c
  tests/flow/test_stress.py
Labels: bug

#1720 replicate graph.config set
  src/commands/cmd_config.c
  tests/flow/test_replication.py
Labels: bug

#1731 Release lock after MergeCreate builds entities
  src/execution_plan/ops/op_merge.c
Labels: bug

#1690 Fiverr logo
  docs/images/logo-fiverr.jpg
  docs/index.md
Labels: Documentation

#1733 Fix link to NRedisGraph github
  docs/clients.md
Labels: Documentation
