Repository RedisGraph/RedisGraph, pull requests merged in 2022-02, with the labels that each got.

#2124 Add documentation for CASE...WHEN, pattern comprehensions, and arithm…
  docs/commands.md
Labels: Documentation

#2126 fix allShortestPaths benchmarks
  tests/benchmarks/allShortestPaths-10hop-100Kpaths.yml
  tests/benchmarks/allShortestPaths-18hop-1Mpaths.yml
  tests/benchmarks/allShortestPaths-4hop-10Kpaths.yml
  tests/benchmarks/allShortestPaths-4hop-25Mpaths.yml
Labels: x:perf

#2127 MOD-2082 Add intershard_tls_pass support
  ramp.yml
Labels: enhancement

#2149 switch to new RediSearch API
  src/filter_tree/ft_to_rsq.c
  tests/flow/test_index_scans.py
Labels: bug

#2154 Add documentation for ResultSet size and run-time configs
  docs/configuration.md
Labels: Documentation

#2161 Document how to set run-time configurations
  docs/configuration.md
Labels: Documentation

#2167 Bind Argument ops to the subplan they belong to
  src/execution_plan/execution_plan_build/execution_plan_modify.c
  tests/flow/test_optional_match.py
Labels: bug

#2176 Fix transfer of SIValue ownership in DISTINCT function
  src/arithmetic/conditional_funcs/conditional_funcs.c
  tests/flow/test_function_calls.py
Labels: bug

#2175 Document how to set run-time configurations
  docs/configuration.md
Labels: Documentation
