Repository RedisGraph/RedisGraph, pull requests merged in 2022-03, with the labels that each got.

#2220 Properly clone WHERE predicates in WITH * projections
  src/ast/ast_rewrite_star_projections.c
  tests/flow/test_star_projections.py
Labels: bug

#2231 Enabled CI profilers
  .circleci/config.yml
Labels: x:quality

#2222 Fix crash on parser errors in queries with RETURN *
  src/ast/ast.c
  src/ast/ast.h
  src/ast/ast_rewrite_star_projections.c
  src/ast/ast_rewrite_star_projections.h
  src/ast/ast_validations.c
  src/commands/execution_ctx.c
  tests/flow/test_query_validation.py
Labels: bug

#2228 Add compile-time and run-time validations for DELETE
  src/ast/ast_validations.c
  src/execution_plan/execution_plan_build/execution_plan_construct.c
  tests/flow/test_graph_deletion.py
Labels: bug

#2233 Allow explicit variables to be returned after a WITH * projection
  src/ast/ast_validations.c
  tests/flow/test_star_projections.py
Labels: bug

#2232 Correctly skip already-deleted edges when enqueuing deletions
  src/graph/graph.c
  tests/flow/test_graph_deletion.py
Labels: bug

#2240 Fix crash on accessing freed label scan member in Reset routine
  src/execution_plan/ops/op_node_by_label_scan.c
  tests/flow/test_graph_merge.py
Labels: bug

#2243 Disable CI profilers until overhead is solved
  .circleci/config.yml
Labels: x:perf

#2242 Fix crash on profiling traversals after op free
  src/execution_plan/ops/op_cond_var_len_traverse.c
  src/execution_plan/ops/shared/print_functions.c
  tests/flow/test_profile.py
Labels: bug
