Repository RedisGraph/RedisGraph, pull requests merged in 2022-04, with the labels that each got.

#2191 WIP content/editorial changes .md
  .github/workflows/trigger-build.yml
  commands.json
  docs/CNAME
  docs/commands/graph.config-get.md
  docs/commands/graph.config-set.md
  docs/commands/graph.delete.md
  docs/commands/graph.explain.md
  docs/commands/graph.list.md
  docs/commands/graph.profile.md
  docs/commands/graph.query.md
  docs/commands/graph.ro_query.md
  docs/commands/graph.slowlog.md
  docs/contrib.md
  docs/docs/References.md
  docs/docs/_index.md
  docs/docs/clients.md
  docs/docs/commands.md
  docs/docs/configuration.md
  docs/docs/cypher_support.md
  docs/docs/datatypes.md
  docs/docs/design/_index.md
  docs/docs/design/bulk_spec.md
  docs/docs/design/client_spec.md
  docs/docs/design/result_structure.md
  docs/docs/images/favicon.png
  docs/docs/images/logo-fiverr.jpg
  docs/docs/images/logo-graphileon.jpg
  docs/docs/images/logo-ibm.jpg
  docs/docs/images/logo-kineviz-graphxr.jpg
  docs/docs/images/logo-linkurious.jpg
  docs/docs/images/logo-mdmetrix.jpg
  docs/docs/images/logo-sidy.jpg
  docs/docs/images/logo-thinkdata.jpg
  docs/docs/images/logo.svg
  docs/docs/images/logo_small.png
  docs/docs/known_limitations.md
  docs/gtm.js
  docs/index.md
  docs/requirements.txt
Labels: Documentation

#2252 Add Project reset routine for single-reply clauses under Cartesian Products
  src/execution_plan/ops/op_project.c
  tests/flow/test_with_clause.py
Labels: bug

#2332 Fixed nightly perf CI module path
  .circleci/config.yml
Labels: skip-changelog

#2318 Fix memory leak
  src/ast/ast_validations.c
Labels: bug

#2319 Fix premature free of ArithmeticExpression members when returning fro…
  src/arithmetic/arithmetic_expression.c
  tests/flow/test_map.py
Labels: bug
