Repository RedisGraph/RedisGraph, pull requests merged in 2023-04, with the labels that each got.

#2826 Effects
  docs/docs/configuration.md
  src/RG.h
  src/commands/cmd_config.c
  src/commands/cmd_constraint.c
  src/commands/cmd_effect.c
  src/commands/cmd_query.c
  src/commands/commands.c
  src/commands/commands.h
  src/configuration/config.c
  src/configuration/config.h
  src/datatypes/array.c
  src/datatypes/array.h
  src/effects/effect_size.c
  src/effects/effects.c
  src/effects/effects.h
  src/effects/effects_apply.c
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/shared/create_functions.c
  src/execution_plan/ops/shared/update_functions.c
  src/graph/entities/attribute_set.c
  src/graph/entities/attribute_set.h
  src/graph/entities/edge.c
  src/graph/entities/edge.h
  src/graph/graph.c
  src/graph/graph.h
  src/graph/graph_hub.c
  src/graph/graph_hub.h
  src/graph/graph_statistics.c
  src/graph/graph_statistics.h
  src/graph/graphcontext.c
  src/module.c
  src/query_ctx.c
  src/query_ctx.h
  src/serializers/decoders/current/v13/decode_graph_entities.c
  src/serializers/decoders/prev/v10/decode_graph_entities.c
  src/serializers/decoders/prev/v11/decode_graph_entities.c
  src/serializers/decoders/prev/v12/decode_graph_entities.c
  src/serializers/decoders/prev/v8/decode_graph_entities.c
  src/serializers/decoders/prev/v9/decode_graph_entities.c
  src/undo_log/undo_log.c
  src/undo_log/undo_log.h
  src/value.c
  src/value.h
  tests/flow/index_utils.py
  tests/flow/test_config.py
  tests/flow/test_constraint.py
  tests/flow/test_edge_index_scans.py
  tests/flow/test_effects.py
  tests/flow/test_replication.py
  tests/unit/test_graph.c
Labels: enhancement, x:perf

#3005 accumulate updates
  src/arithmetic/arithmetic_expression.c
  src/arithmetic/string_funcs/string_funcs.c
  src/commands/cmd_query.c
  src/datatypes/array.c
  src/datatypes/array.h
  src/effects/effect_size.c
  src/effects/effects.c
  src/effects/effects.h
  src/effects/effects_apply.c
  src/execution_plan/ops/op_create.c
  src/execution_plan/ops/op_delete.c
  src/execution_plan/ops/op_delete.h
  src/execution_plan/ops/op_merge.c
  src/execution_plan/ops/op_merge.h
  src/execution_plan/ops/op_update.c
  src/execution_plan/ops/op_update.h
  src/execution_plan/ops/shared/create_functions.c
  src/execution_plan/ops/shared/create_functions.h
  src/execution_plan/ops/shared/update_functions.c
  src/execution_plan/ops/shared/update_functions.h
  src/execution_plan/optimizations/optimize_cartesian_product.c
  src/graph/entities/attribute_set.c
  src/graph/entities/attribute_set.h
  src/graph/graph_hub.c
  src/graph/graph_hub.h
  src/query_ctx.c
  src/query_ctx.h
  src/undo_log/undo_log.c
  src/undo_log/undo_log.h
  src/util/arr.h
  src/util/dict.c
  src/util/dict.h
  src/value.c
  src/value.h
  tests/flow/test_entity_update.py
  tests/flow/test_foreach.py
  tests/flow/test_graph_deletion.py
Labels: action:run-benchmark

#3070 Reattach on reset
  src/execution_plan/ops/op_node_by_label_scan.c
  src/graph/rg_matrix/rg_matrix_iter.c
  src/util/range/unsigned_range.c
Labels: bug
